fix : share stil highlighted after cancel
openMF/self-service-app pull request #1006
Opened 2019-01-22 21:38 UTC by shiv07tiwari

Fixes #1004 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2019-01-22 21:39 UTC, shiv07tiwari commented
@luckyman20 @miPlodder

2019-01-23 09:44 UTC, luckyman20 commented
Fix your PR heading

2019-01-23 09:51 UTC, shiv07tiwari commented
@luckyman20 fixed it.

2019-01-23 12:30 UTC, luckyman20 approved these changes
Looks good! Great job @shiv07tiwari

2019-01-31 21:14 UTC, shiv07tiwari commented
@miPlodder @therajanmaurya Kindly review this PR.

2019-02-07 17:56 UTC, miPlodder requested changes

2019-02-07 17:56 UTC, miPlodder commented on app/src/main/java/org/mifos/mobilebanking/ui/activities/HomeActivity.java
> +        setNavigationViewSelectedItem(R.id.item_home);
@shiv07tiwari The changes you have made are incorrect. You cannot always change the selected Navigation Item to `Home` on `onResume()` method. Checkout Activity lifecycle, `onResume()` method is called many times.

A simple scenario whereas you solution will fail will be Go to `Charges > Open Another App > Now open Self-Service App > Charges Fragment` will be displayed and Home Navigation will be selected.

2019-02-18 07:29 UTC, shiv07tiwari commented
@miPlodder @luckyman20 Kindly review this. I added a check for item initially highlighted which solves the issue.

2019-02-22 01:12 UTC, shiv07tiwari commented
@miPlodder @nikit19 @therajanmaurya Kindly review this.

2019-03-04 10:18 UTC, shiv07tiwari commented
@miPlodder @therajanmaurya Kindly review this.

2019-03-25 00:19 UTC, shiv07tiwari commented
@therajanmaurya Fixed the merge conflict.

2019-05-22 18:22 UTC, prashantkh19 commented
@shiv07tiwari I couldn't reproduce this issue, maybe some other merged PR fixed this. Can you confirm?
If yes, please close this PR.

2019-05-22 18:23 UTC, prashantkh19 commented
If you still find this issue, please share a gif of the same.

2019-06-02 10:35 UTC, therajanmaurya commented
It does not exists anymore.

2019-06-02 10:35 UTC, closed without merging