fix : share link
openMF/self-service-app pull request #1033
Opened 2019-01-30 19:05 UTC by shiv07tiwari

Fixes #1005 
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2019-01-31 18:08 UTC, therajanmaurya requested changes

2019-01-31 18:08 UTC, therajanmaurya commented on app/src/main/res/values/strings.xml
> +    <string name="string_and_string_share">%1$s%2$s</string>
Yeah good catch but we can't name it with share, I would suggest make it specially for share link. 

<string name="playstore_link">%1$s%2$s</string>

something.

2019-01-31 20:30 UTC, shiv07tiwari commented
Made the changes @therajanmaurya

2019-02-01 04:05 UTC, therajanmaurya approved these changes

2019-02-01 04:05 UTC, merged