Update README.md
openMF/self-service-app pull request #1037
Opened 2019-02-11 10:06 UTC by RajaVamsi11

Fixes #557 

Updated Readme file so that new contributors can find easy to start contributing.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2019-02-11 10:43 UTC, RajaVamsi11 commented
@miPlodder @therajanmaurya Can you please review this PR.

2019-02-20 08:29 UTC, therajanmaurya requested changes

2019-02-20 08:29 UTC, therajanmaurya commented on README.md
> +# Self Service Android Application for MifosX
We have changed the name Self Service -> Mifos Mobile, So It should be  Mifos-Mobile Android Application for MifosX

2019-02-20 08:29 UTC, therajanmaurya commented on README.md
> +For Issue tracker guidelines please click <a href="https://github.com/openMF/mifos-mobile/blob/development/.github/CONTRIBUTING.md">here</a>. All fixes should be proposed via pull requests.
Fix the Issue template link: https://github.com/openMF/mifos-mobile/blob/development/.github/ISSUE_TEMPLATE.md

2019-02-20 17:58 UTC, RajaVamsi11 commented
@therajanmaurya Updated according to the changes suggested.

2019-03-01 10:04 UTC, therajanmaurya approved these changes

2019-03-01 10:04 UTC, merged