feat: add confirmayion in passcode to password login
openMF/self-service-app pull request #1063
Opened 2019-02-20 21:14 UTC by shiv07tiwari

Fixes #1057

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2019-02-20 21:15 UTC, shiv07tiwari commented
![videotogif_2019 02 21_02 34 57](https://user-images.githubusercontent.com/38163725/53124935-b3331200-3582-11e9-84eb-833b619c68d0.gif)

2019-02-22 01:01 UTC, shiv07tiwari commented
@miPlodder Kindly review this.

2019-03-01 10:08 UTC, therajanmaurya requested changes
Fix the conflicts and make changes as requested

2019-03-01 10:08 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/ui/activities/PassCodeActivity.java
> +        AlertDialog.Builder builder = new AlertDialog.Builder(PassCodeActivity.this);
Use Material Dialog class in utils/ directory

2019-03-04 10:27 UTC, shiv07tiwari commented
@therajanmaurya Made the changes.

2019-03-05 23:04 UTC, shiv07tiwari commented
@therajanmaurya Fixed the build

2019-03-25 00:21 UTC, shiv07tiwari commented
@therajanmaurya Fixed the merge conflict.

2023-05-15 21:38 UTC, luckyman20 commented
Closing this as the issue is already solved.

2023-05-15 21:38 UTC, closed without merging