Beneficiaries appearance has been corrected
openMF/self-service-app pull request #1067
Opened 2019-02-22 14:09 UTC by atm1504

Fixes #1066 

Please Add Screenshots If there are any UI changes.
![benefic](https://user-images.githubusercontent.com/43731599/53247478-7e859e80-36d9-11e9-921d-d31080de7dff.jpeg)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2019-03-01 10:03 UTC, therajanmaurya commented
Yeah make sense, Please follow commit style guideline https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide

2019-03-03 12:07 UTC, miPlodder commented
@atm1504 I don't think the solution to this PR is custom. Try adding generic solution. The hard-coded value of margin are working on you device, but won't work on other devices.

2019-03-03 12:31 UTC, miPlodder requested changes
@atm1504 Make these changes.

2019-03-03 12:31 UTC, miPlodder commented on app/src/main/res/layout/fragment_home_old.xml
> +
Remove this space.

2019-03-03 12:31 UTC, miPlodder commented on app/src/main/res/layout/fragment_home_old.xml
> +                            android:layout_marginLeft="16sp"
Change the `sp` to `dp` for both the margins

2019-03-03 12:31 UTC, miPlodder commented on app/src/main/res/layout/fragment_home_old.xml
> +                            android:padding="0dp"
I don't think `padding` is needed, default padding of TextView is 0dp only. Check it and make changes accordingly here.

2019-03-03 12:35 UTC, miPlodder commented
@atm1504 Also change the Commit message to `Fix#1066 : <rest-commit-message>` as suggested by @therajanmaurya .

2019-05-23 08:46 UTC, prashantkh19 commented
@atm1504 can you make the suggested changes?

2019-06-06 07:14 UTC, prashantkh19 commented
@therajanmaurya No significant changes and the changes are also not done. I guess, we can close this.

2020-11-20 20:22 UTC, closed without merging