Added checks for login fields and some tweaks
openMF/self-service-app pull request #113
Opened 2017-03-02 20:25 UTC by Pritom14

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2017-03-02 20:26 UTC, Pritom14 commented
@therajanmaurya Sir, I have done as you said, can you please review it

2017-03-03 09:18 UTC, therajanmaurya requested changes

2017-03-03 09:18 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/presenters/LoginPresenter.java
> +            showMinimumInputLengthNotAchievedError("Username",
Revert back these changes you can not use hard coded string. I have looked it was written in good manner.

2017-03-03 09:18 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/presenters/LoginPresenter.java
> +            getMvpView().showMessage("Username cannot contain white spaces");
Revert back this change, It's unnecessary.

2017-03-03 09:18 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/presenters/LoginPresenter.java
> +            showEmptyInputError("Password cannot be empty");
Revert back this change, It's unnecessary.

2017-03-03 09:18 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/presenters/LoginPresenter.java
> +            showMinimumInputLengthNotAchievedError("Password",
Revert back this change, It's unnecessary.

2017-03-03 09:21 UTC, therajanmaurya requested changes

2017-03-03 09:21 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/presenters/LoginPresenter.java
>          getMvpView().showProgress();
Remove this line, Do not need to show Progressbar before validating the username or password.

2017-03-03 09:21 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/presenters/LoginPresenter.java
> +            getMvpView().hideProgress();
No need to hide ProgressBar Unnecessary.

2017-03-03 09:26 UTC, Pritom14 commented on app/src/main/java/org/mifos/selfserviceapp/presenters/LoginPresenter.java
> +            getMvpView().hideProgress();
@therajanmaurya Sir,Can I submit a new PR

2017-03-03 09:43 UTC, closed without merging