Fix #1199 - Blank screen in Account Activity
openMF/self-service-app pull request #1200
Opened 2019-10-09 17:52 UTC by devansh-299

Fixes #1199 

Screen Recording

![fix1199](https://user-images.githubusercontent.com/46667021/66506723-80c32e80-eaeb-11e9-93af-6a7ea68f8a4e.gif)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2019-10-13 05:56 UTC, geekanamika commented on app/src/main/res/values/strings.xml
> +
One line space will suffice, you can remove on extra line after strings.

2019-10-13 06:07 UTC, geekanamika requested changes
I would recommend using "showSweetCustomErrorUI" method from SweetUIErrorHandler to display appropriate image & message when filter search results with no data. No need to add addition imageview & text, handle it's visibility throughout the code. 
Can you please update the PR?

2019-10-17 14:31 UTC, devansh-299 commented
@geekanamika , I updated the PR as requested but the Travis build failed stating the cause as *java.lang.IllegalArgumentException: Unable to exclude rules [GuardLogStatement];*

2019-10-20 17:48 UTC, devansh-299 commented
@geekanamika  I have updated the PR , please review it

2019-11-24 10:55 UTC, geekanamika requested changes
Added two comments. 
For future PRs, Please don't add any file which doesn't have any relevant changes related to the PR/issue. Thanks :)

2019-11-24 10:55 UTC, geekanamika commented on gradle/wrapper/gradle-wrapper.properties
> +#Thu Oct 17 16:49:19 IST 2019
remove comment changes here.

2019-11-24 10:55 UTC, geekanamika commented on app/src/main/AndroidManifest.xml
> +            android:launchMode="singleTask"
There's no change in this file, why format & add it in a commit? 
Please remove this file from the commit.

2019-11-24 13:01 UTC, devansh-299 commented
> Added two comments.
> For future PRs, Please don't add any file which doesn't have any relevant changes related to the PR/issue. Thanks :)

Thanks for the advice . I won't repeat this mistake

2019-11-24 16:19 UTC, geekanamika approved these changes

2019-11-24 16:19 UTC, merged