Removed hardcoded dimens from all xml layout files
openMF/self-service-app pull request #1232
Opened 2019-12-02 21:26 UTC by OussEmaDevCode

Fixes #1231 

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2019-12-03 05:57 UTC, zoman-anamika commented on app/src/main/res/layout/fragment_add_loan_application.xml
> +                    android:layout_width="@dimen/width_none"
Use dimen_0dp instead of width_none as name.

2019-12-03 05:59 UTC, geekanamika commented on app/src/main/res/layout/fragment_account_overview.xml
> +                        android:textSize="@dimen/text_headline"
Rename it to text_size_headline

2019-12-03 05:59 UTC, geekanamika commented on app/src/main/res/layout/fragment_account_overview.xml
> +                        android:textSize="@dimen/text_smaller"
Similar, text_size_smaller

2019-12-03 05:59 UTC, geekanamika commented on app/src/main/res/layout/fragment_accounts.xml
> +            android:layout_height="@dimen/height_none"
Update it to dimen_0dp

2019-12-03 06:01 UTC, geekanamika commented on app/src/main/res/layout/fragment_add_loan_application.xml
> +                android:paddingTop="@dimen/layout_padding_10dp"
As you have followed earlier, use id_name with padding like sp_loan_padding_top

2019-12-03 06:03 UTC, geekanamika commented on app/src/main/res/layout/fragment_guarantor_detail.xml
> +        android:layout_height="@dimen/detail_height"
use dimen_1dp instead as it's not particular to view.

2019-12-03 06:04 UTC, geekanamika requested changes
Good work :D I have added few single line comments, can you update private accordingly?

2019-12-03 10:09 UTC, OussEmaDevCode commented
I have updated according to what you sad, thanks for the feedback 😃

2019-12-03 10:54 UTC, geekanamika reviewed
Looks good to me.

2020-05-22 06:17 UTC, ShivangiSingh17 approved these changes

2023-03-22 13:31 UTC, closed without merging