Fix : Add No internet page for Applying for new Savings Account  #1123
openMF/self-service-app pull request #1255
Opened 2019-12-21 07:01 UTC by SkroX

Fixes #1123 

Please Add Screenshots If there are any UI changes.
![Screenshot_20191221_122415_org mifos mobile](https://user-images.githubusercontent.com/43489760/71304479-5c3dd980-23ed-11ea-9dc5-f321231a4cff.jpg)
![Screenshot_20191221_122425_org mifos mobile](https://user-images.githubusercontent.com/43489760/71304482-695ac880-23ed-11ea-9879-12443a39a399.jpg)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2019-12-22 15:34 UTC, SkroX commented
@luckyman20 can you please review and approve this pull request. Thanks!

2019-12-23 17:49 UTC, luckyman20 requested changes

2019-12-23 17:49 UTC, luckyman20 commented on app/src/main/java/org/mifos/mobile/ui/fragments/SavingsAccountApplicationFragment.java
> +            Toast.makeText(getContext(), getString(R.string.internet_not_connected),
Remove Toast since you are already showing the error on the screen.

2019-12-23 17:49 UTC, luckyman20 commented on app/src/main/java/org/mifos/mobile/ui/fragments/SavingsAccountApplicationFragment.java
> +            Toast.makeText(getContext(), error, Toast.LENGTH_SHORT).show();
Here too.

2019-12-23 17:49 UTC, luckyman20 commented on app/src/main/java/org/mifos/mobile/ui/fragments/SavingsAccountApplicationFragment.java
> +            Toast.makeText(getContext(), getString(R.string.internet_not_connected),
Use our in-house lib Toaster instead which resides in Utils package.

2023-06-05 14:41 UTC, closed without merging