Fixes issue #920. The splash screen doesn't stretch anymore
openMF/self-service-app pull request #1269
Opened 2020-01-13 06:31 UTC by devanshi7799

Fixes #I920

Please Add Screenshots If there are any UI changes.
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/51824493/72236324-658d2100-35fc-11ea-89dc-f05d06c7dd08.gif)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2020-01-14 15:22 UTC, devansh-299 requested changes
Just adding the drawable file won't work . I would suggest you to refer the below link or any similar solution you can find and make the changes accordingly 
https://android.jlelse.eu/the-complete-android-splash-screen-guide-c7db82bce565

2020-01-21 16:57 UTC, laxyapahuja commented
@devanshi7799 It seems like you've done the changes for #676 in this branch only. I'd suggest you to revert back to the last commit and do changes in a different branch.

2020-01-21 16:59 UTC, devanshi7799 commented
@laxyapahuja yaa sorry, I mixed up two different issues :/

2020-01-21 19:06 UTC, devansh-299 commented on app/src/main/res/layout/fragment_home_old.xml
> +                        android:textAppearance="@style/Base.TextAppearance.AppCompat.Small"
This change is not related to this PR, kindly undothis change

2020-01-21 19:06 UTC, devansh-299 commented on app/src/main/res/values/strings.xml
> +    <string name="help_line_number" translatable="false">+18000000000</string>
Please don't change the helpline number

2020-01-21 19:08 UTC, devansh-299 commented
Please do the suggested changes and squash all your commits

2020-05-17 14:55 UTC, ShivangiSingh17 commented
@devanshi7799 can you please squash all your commits.

2020-05-22 04:56 UTC, ShivangiSingh17 reviewed
The changes made aren't giving the expected results.

2020-11-20 20:12 UTC, closed without merging