Fixing incorrect icon shown  issue#1316
openMF/self-service-app pull request #1331
Opened 2020-02-12 17:30 UTC by som23ya

replacement with assignment_not_turned icon

Fixes #Issue_Number

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2020-02-13 04:45 UTC, devansh-299 commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:3.5.0'
this change is not required please remove this from commit

2020-02-13 04:46 UTC, devansh-299 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
Same goes for this file

2020-03-02 19:21 UTC, devansh-299 requested changes

2020-03-02 19:21 UTC, devansh-299 commented on gradle/wrapper/gradle-wrapper.properties
> +#Mon Feb 10 02:05:55 IST 2020
please remove this change as it is unnecessary and squash all your commits
rest everything seems fine

2020-03-02 20:36 UTC, som23ya reviewed
@devansh-299 thanks for the guidance. :D please review this.

2020-03-03 07:52 UTC, devansh-299 approved these changes

2020-03-03 07:55 UTC, devansh-299 commented
Please squash your commits.

2020-05-22 03:19 UTC, ShivangiSingh17 approved these changes

2023-06-03 06:25 UTC, luckyman20 commented
Issue has already been resolved.

2023-06-03 06:25 UTC, closed without merging