Added Dynamic Shortcuts
openMF/self-service-app pull request #1369
Opened 2020-02-22 09:32 UTC by nirmalhk7

Added dynamic shortcuts, visisble only if viewed from device having Android newer than Nougat 7.1. Other devices will be unharmed.
I've chosen 4 shortcuts here, please let me know if I should choose 4 different ones.

Signed-off-by: Nirmal Khedkar <nirmalhk7@gmail.com>

Fixes #923 

Please Add Screenshots If there are any UI changes.
![untitled](https://user-images.githubusercontent.com/25480443/75089988-5054cc00-5584-11ea-8de2-35525539e6d7.gif)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything
- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-02-22 22:31 UTC, devansh-299 commented
@nirmalhk7 these shortcuts introduce a very serious problem of bypassing the verification steps while opening the app through them. I also faced similar problem while trying to add shortcuts

2020-02-23 13:53 UTC, nirmalhk7 commented
@devansh-299 Thanks for pointing out! I totally forgot about them. Bypassing security would indeed be quite a serious bug.

Since I'll be doing these dynamically, my idea to solve it is to let the shortcuts all point at `SplashActivity` (which points to `PasscodeActivity`). I'll save the option menu needed using `setAction()` function (the string will be the name of the menu).

So once you click a shortcut, you'd be directed to the `SplashActivity`, from there the `PasscodeActivity` and from there the `HomeActivity`. Before loading the `HomeOldFragment`, we check if `getAction()` has our menus (I've noticed that if it doesnt, its default value is `_android.intent.action.MAIN_`). If it does, we load our option as if it's been loaded from the Navigation Drawer, else we load the `HomeOldFragment`.

I've implemented all that I've set above, and in my testing, it works well. I'll fix the build errors, clean up the code and will push by tonight.

2020-02-23 14:41 UTC, nirmalhk7 commented
Please review this PR.

Here is the final output (the lag is because I'm using Emulator):

![untitled](https://user-images.githubusercontent.com/25480443/75114020-9f7c2900-5678-11ea-88e6-521a313db6d7.gif)

2020-02-23 16:43 UTC, devansh-299 commented on app/src/main/java/org/mifos/mobile/ui/activities/HomeActivity.java
> +        Log.d("NIRMALHK7","HomeActiv "+getIntent().getAction());
you can remove this once you have tested

2020-02-23 16:46 UTC, devansh-299 commented on app/src/main/java/org/mifos/mobile/ui/activities/HomeActivity.java
> +                    new ShortcutInfo.Builder(this, "forth_shortcut")
create string resources for "forth_shortcut"  and others

2020-02-23 16:48 UTC, devansh-299 commented on app/src/main/java/org/mifos/mobile/ui/activities/HomeActivity.java
> +                            .setShortLabel("3rd Party Transfer.")
Same here, use string resource files  wherever necessary

2020-02-23 16:50 UTC, devansh-299 commented on app/src/main/java/org/mifos/mobile/ui/activities/PassCodeActivity.java
> +        if(getIntent().getAction()!=null && !getIntent().getAction().trim().equals("android.intent.action.MAIN"))
You can create a constant string inside  `util/Constants.java` for "android.intent.action.MAIN"

2020-02-23 16:50 UTC, devansh-299 commented on app/src/main/java/org/mifos/mobile/ui/activities/SplashActivity.java
> +            Log.d("NIRMALHK7","SplashAct "+getIntent().getAction());
please remove this

2020-02-23 16:55 UTC, devansh-299 commented
@nirmalhk7 nice work!
You have 3 checkstyle violations because of which your build is failing the tests
You can checkout the violations here `../mifos-mobile/app/build/reports/checkstyle/checkstyle.html`

2020-02-24 02:41 UTC, nirmalhk7 commented
Just fixed all your above suggestions. Please review the latest push. I get a build error for reasons I cant understand ` error: cannot find symbol import org.mifos.mobile.injection.component.DaggerActivityComponent;
`. I've asked on some of the gitter channels and people suggested me to do "Clean Project", which hasn't really helped a lot. 

Regardless, I've pushed the code. If theres anything I could do about build, let me know. Thanks!

2020-02-24 09:53 UTC, robustTechie commented on app/src/main/java/org/mifos/mobile/ui/activities/SplashActivity.java
> +
Is this space required?

2020-02-24 09:53 UTC, robustTechie commented on app/src/main/res/values/strings.xml
> +
Here also

2020-02-24 09:53 UTC, robustTechie commented on app/src/main/res/values/strings.xml
> +    <string name="defaultAction">android.intent.action.MAIN</string>
After string array leave a space of one line.

2020-02-24 09:53 UTC, robustTechie commented on app/src/main/java/org/mifos/mobile/ui/activities/PassCodeActivity.java
> +    private String actions;
Leave a line space after this.

2020-02-24 09:53 UTC, robustTechie commented on app/src/main/java/org/mifos/mobile/ui/activities/SplashActivity.java
> +
All these imports are required?

2020-02-24 11:33 UTC, devansh-299 requested changes

2020-02-24 11:33 UTC, devansh-299 commented on app/src/main/java/org/mifos/mobile/ui/activities/HomeActivity.java
> +import android.net.Uri;
remove this as this import is unused

2020-02-24 11:33 UTC, devansh-299 commented on app/src/main/java/org/mifos/mobile/ui/activities/HomeActivity.java
> +import androidx.annotation.NonNull;
same here, unused import

2020-02-24 11:33 UTC, devansh-299 commented on app/src/main/java/org/mifos/mobile/ui/activities/HomeActivity.java
> +import androidx.annotation.Nullable;
this also

2020-02-24 11:33 UTC, devansh-299 commented on app/src/main/java/org/mifos/mobile/ui/activities/HomeActivity.java
> +import java.util.Arrays;
same goes for this line, 64, 65 and 67 line

2020-02-24 11:33 UTC, devansh-299 commented on app/src/main/java/org/mifos/mobile/ui/activities/PassCodeActivity.java
> +import android.util.Log;
remove this

2020-02-24 11:33 UTC, devansh-299 commented on app/src/main/java/org/mifos/mobile/ui/activities/SplashActivity.java
> +import android.content.pm.ShortcutInfo;
remove the following imports as these aren't being used :- 8, 9 , 10, 12, 18, 19, 20, 21, 22, 23, 26, 27 (these are line numbers)

2020-02-26 05:21 UTC, robustTechie commented
Great you added all this feature, but I have a one suggestion there is no uninstall and remove option, so add it also.

2020-02-26 19:30 UTC, nirmalhk7 commented
> Great you added all this feature, but I have a one suggestion there is no uninstall and remove option, so add it also.

@robustTechie [Android's documentation on shortcuts](https://developer.android.com/guide/topics/ui/shortcuts) states that we can implement only four shortcuts at the maximum. So I dont think that is possible without changing the 4 existing shortcuts implemented as well.

2023-06-03 06:30 UTC, closed without merging