New Feature: Passcode Added ISSUE #132
openMF/self-service-app pull request #151
Opened 2017-03-07 13:54 UTC by shivamarora96

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2017-03-07 17:09 UTC, therajanmaurya requested changes

2017-03-07 17:09 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/presenters/LoginPresenter.java
> +                            sp.edit().commit();
@shivamarora96 Please use utils/PreManager.class. don't need to make SharedPreferences object.

2017-03-07 17:09 UTC, therajanmaurya commented
@shivamarora96 Please make above change and Squash your commits and force push again then i will look the logic of the implementation.

2017-03-07 17:55 UTC, shivamarora96 commented on app/src/main/java/org/mifos/selfserviceapp/presenters/LoginPresenter.java
> +                            sp.edit().commit();
@therajanmaurya 

1.There is no such file named PreManager.class under util. Are you talking about api/local/PreferencesHelper?

2. **If you are talking about api/local/PreferencesHelper**, then what is the need for change ?

2017-03-08 08:37 UTC, shivamarora96 commented on app/src/main/java/org/mifos/selfserviceapp/presenters/LoginPresenter.java
> +                            sp.edit().commit();
@therajanmaurya ?

2017-03-10 12:32 UTC, closed without merging

2017-03-12 13:01 UTC, hardik124 commented
@therajanmaurya  can I take up this issue?