Update fabric crashlytics to firebase crashlytics
openMF/self-service-app pull request #1603
Opened 2020-12-01 10:20 UTC by Sparsh1212

Fixes #1553 

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-12-01 10:28 UTC, Sparsh1212 commented
@miPlodder @devansh-299 Please review.

2020-12-01 10:47 UTC, garvit984 commented
@Sparsh1212 Please squash all the commits into a single commit.

2020-12-01 10:57 UTC, Sparsh1212 commented
> @Sparsh1212 Please squash all the commits into a single commit.

Done!

2020-12-03 18:02 UTC, miPlodder requested changes
- Take care of the comments given
- Also, add #issue-id in your commit message, so we can get to know what issue does it resolve. (from commit-msg)

2020-12-03 18:02 UTC, miPlodder commented on app/build.gradle
> +    implementation 'com.google.firebase:firebase-crashlytics:17.3.0'
Let's follow the standard practice of defining versions at one place, and then using them.

2020-12-03 18:02 UTC, miPlodder commented on build.gradle
> +        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
Let's use a variable from versions, let's do the same for other classpath dependencies also, which are missed as I see.

2020-12-06 20:12 UTC, Sparsh1212 commented
> * Take care of the comments given
> * Also, add #issue-id in your commit message, so we can get to know what issue does it resolve. (from commit-msg)

Please review the updated changes.

2020-12-10 18:31 UTC, miPlodder approved these changes
Looks Good.
Nice job

2020-12-10 18:31 UTC, merged