Fixes #1073: Toast message in Recent Transactions fixed
openMF/self-service-app pull request #1630
Opened 2020-12-17 05:56 UTC by PatelVatsalB21

Fixes #1073 

![GIF-201217_111940 1](https://user-images.githubusercontent.com/70195106/102449436-4263c080-405a-11eb-88bc-d39e9b1ee7a8.gif)

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-12-17 06:13 UTC, PatelVatsalB21 commented
@miPlodder plz review this pr.

2020-12-25 18:31 UTC, miPlodder requested changes

2020-12-25 18:31 UTC, miPlodder commented on app/src/main/java/org/mifos/mobile/ui/fragments/RecentTransactionsFragment.kt
> +                                newState==RecyclerView.SCROLL_STATE_IDLE) {
format the code before pushing in IDE

2020-12-25 19:14 UTC, PatelVatsalB21 commented
@miPlodder please review changes

2020-12-26 17:42 UTC, miPlodder approved these changes

2020-12-26 17:43 UTC, merged