Fix #1661: In Register Activity. Validator code missing for Phone Number
openMF/self-service-app pull request #1662
Opened 2020-12-29 08:37 UTC by ritish099

Fixes #1661

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

<img src="https://user-images.githubusercontent.com/54978105/103270907-11cb4180-49df-11eb-92d4-05349e15eb67.jpg" width="333">

2020-12-29 08:37 UTC, ritish099 commented
@miPlodder Kindly check it out....

2021-01-10 12:28 UTC, miPlodder requested changes
Nice Job, format your code. rest looks fine

2021-01-10 12:28 UTC, miPlodder commented on app/src/main/java/org/mifos/mobile/ui/fragments/RegistrationFragment.kt
> +        }else if (etPhoneNumber?.text.toString().trim { it <= ' ' }.isEmpty()) {
i see formatting is not perfect. `ctrl+alt+L` in your IDE before pushing

2021-01-10 14:12 UTC, ritish099 commented
@miPlodder reformatting does not change anything. I did some things manually kindly check it out.

2023-06-03 11:58 UTC, luckyman20 commented
The issue is already resolved.

2023-06-03 11:58 UTC, closed without merging