fix: #1694 Recycler view behaviour rectified
openMF/self-service-app pull request #1696
Opened 2021-01-13 11:49 UTC by divyank00

Fixes #Issue_Number

Please Add Screenshots If there are any UI changes.

https://user-images.githubusercontent.com/50913976/104448718-85ff0b00-55c3-11eb-8be2-f373d9d8d6de.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2021-01-13 17:58 UTC, PatelVatsalB21 reviewed
@divyank00 can u place error number in pr details where it is written as "Fixes #Issue_Number"

2021-01-13 20:01 UTC, PatelVatsalB21 approved these changes
LGTM

2021-01-14 07:47 UTC, divyank00 commented
@miPlodder Can you please review this

2021-01-16 19:00 UTC, miPlodder requested changes
- Can you explain you what was wrong in PR description based on your analysis?
- Can you update this file,
https://github.com/openMF/mifos-mobile/blob/development/.github/PULL_REQUEST_TEMPLATE.md and 
add `Please add Fixture Analysis for your PR` and `Please add stacktrace in case of crashes` on Line 2 and 3 respective

2021-01-17 04:16 UTC, divyank00 commented
> * Please add Fixture Analysis for your PR

Changes have been made. Do you want me to update .md file for the whole repository or only this pr?

2021-01-17 04:37 UTC, divyank00 commented
> - Can you explain you what was wrong in PR description based on your analysis?
> - Can you update this file,
> https://github.com/openMF/mifos-mobile/blob/development/.github/PULL_REQUEST_TEMPLATE.md and 
> add `Please add Fixture Analysis for your PR` and `Please add stacktrace in case of crashes` on Line 2 and 3 respective

Changes have been made. Do you want me to update .md file for the whole repository or only this pr? Can you review it.

2021-01-18 11:38 UTC, miPlodder commented
Yes, change the template files for the PR. Make heading bold, just to ensure better readibility

2021-01-18 11:40 UTC, divyank00 commented
@miPlodder made the changes

2023-04-29 18:55 UTC, closed without merging