Fix: SnackBar instead of toast if internet is not connected in charge…
openMF/self-service-app pull request #173
Opened 2017-03-11 18:12 UTC by Rishabhk07

…s fragment, fixes #168

Signed-off-by: Rishabh Khanna <rishabhkhanna777@gmail.com>

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2017-03-12 18:32 UTC, Rishabhk07 commented
@therajanmaurya please review. Thanks :)

2017-03-13 08:11 UTC, therajanmaurya requested changes

2017-03-13 08:11 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/ui/fragments/ClientChargeFragment.java
> +        Toaster.show(getView() , message);
@Rishabhk07 remove the getView() and pass the `rooView` as a parameter.

2017-03-13 20:47 UTC, Rishabhk07 commented on app/src/main/java/org/mifos/selfserviceapp/ui/fragments/ClientChargeFragment.java
> +        Toaster.show(getView() , message);
@therajanmaurya Fixed the changes, used rootView instead of getView().

2017-03-14 07:34 UTC, therajanmaurya approved these changes

2017-03-14 07:34 UTC, merged