feat: Deposit in SavingsAccount Details
openMF/self-service-app pull request #175
Opened 2017-03-12 05:19 UTC by Pritom14

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2017-03-12 05:25 UTC, Pritom14 commented
@therajanmaurya , Sir please have a look at this

2017-03-13 08:05 UTC, therajanmaurya requested changes

2017-03-13 08:05 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/ui/activities/SavingsAccountContainerActivity.java
> +                false, R.id.container);
Why you are passing Savings Accounts Id twice. Please revert back these changes.

2017-03-13 08:05 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/ui/fragments/SavingAccountsDetailFragment.java
> +            accountId = getArguments().getLong(Constants.ACCOUNT_ID);
Revert back these changes because we already passing the SavingsAccount Id. don't need to pass thing twice. It's useless.

2017-03-13 08:05 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/ui/fragments/SavingAccountsDetailFragment.java
> +        ((BaseActivity) getActivity()).replaceFragment(SavingsMakeTransferFragment
These changes that I want in this PR

2017-03-13 08:06 UTC, therajanmaurya commented
Please Include the screen shot.

2017-03-13 09:22 UTC, closed without merging

2017-03-13 09:23 UTC, therajanmaurya commented
Added in #175