Fix #1756: Change Password Button not working properly
openMF/self-service-app pull request #1757
Opened 2021-03-02 09:38 UTC by ritish099

Fixes #1756

Please Add Screenshots If there are any UI changes.

https://user-images.githubusercontent.com/54978105/109628698-0f18d400-7b69-11eb-84b8-3cb3d1375a6b.mp4

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2021-03-02 17:33 UTC, jddeep requested changes

2021-03-02 17:33 UTC, jddeep commented on app/src/main/res/values/strings.xml
> +    <string name="key">Password</string>
give it a suitable name. How about trying `password_key`

2021-03-03 17:21 UTC, PatelVatsalB21 reviewed
@ritish099 please check with './gradlew check' --scan' before commit.

2021-03-03 17:24 UTC, ritish099 commented
@PatelVatsalB21 I cannot figure out. what's the problem.. U can see the PR. There is no such changes.. and just cloning the development branch and running "./gradlew check" is creating a problem. Can u help me?

2021-03-03 17:29 UTC, PatelVatsalB21 commented
Yes I know that, it seems annotation error, clean and rebuild your project and try force push, it might help you. Sometimes it happens like this

2023-06-03 12:07 UTC, closed without merging