theme changes according to system theme
openMF/self-service-app pull request #1929
Opened 2023-02-26 18:49 UTC by PratyushSingh07

Fixes #1928 

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2023-03-22 14:35 UTC, PratyushSingh07 commented
@jawidMuhammadi fixed this one as well , kindly have a look and incase of any changes let me know

2023-03-22 22:33 UTC, jawidMuhammadi requested changes

2023-03-22 22:33 UTC, jawidMuhammadi commented on app/src/main/java/org/mifos/mobile/ui/activities/PassCodeActivity.kt
> +        ll.setBackgroundColor(android.R.attr.colorBackground)
I believe you could set this value directly in the XML file, could you try that?

2023-03-23 03:56 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/activities/PassCodeActivity.kt
> +        ll.setBackgroundColor(android.R.attr.colorBackground)
the xml for this activity is in reader mode for some reason , and when i try to modify it i get the below check box
![image](https://user-images.githubusercontent.com/90026952/227098897-fff55926-de85-4bea-84f9-93975d34d96c.png)
So , I'm not really sure if I should make any changes over here and that is why I am changing it programatically

2023-03-24 15:07 UTC, jawidMuhammadi commented on app/src/main/java/org/mifos/mobile/ui/activities/PassCodeActivity.kt
> +        ll.setBackgroundColor(android.R.attr.colorBackground)
Oh, then it is okay, but you need to reformat your code first.

2023-03-24 17:17 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/activities/PassCodeActivity.kt
> +        ll.setBackgroundColor(android.R.attr.colorBackground)
i have reformatted my code , kindly check if this is acceptable . If its decent then I will squash the commits as well

2023-03-29 12:26 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/activities/PassCodeActivity.kt
> +        ll.setBackgroundColor(android.R.attr.colorBackground)
i have reformatted the code , kindly review it

2023-04-06 19:55 UTC, PratyushSingh07 commented
@jawidMuhammadi I had reformatted my code in this PR . Are the modifications upto the mark ? If not, then do let me know what else I could do to rectify them . I will learn a lot from this

2023-04-10 15:40 UTC, jawidMuhammadi requested changes

2023-04-10 15:40 UTC, jawidMuhammadi commented on app/src/main/java/org/mifos/mobile/ui/activities/PassCodeActivity.kt
> +        val nestedScrollView = findViewById<NestedScrollView>(R.id.cl_rootview)
Why not ButterKnife instead of findeViewById()?

2023-04-10 15:40 UTC, jawidMuhammadi commented on app/src/main/java/org/mifos/mobile/ui/activities/PassCodeActivity.kt
> +        theme.resolveAttribute(colorBackground, typedValue, true)
Instead of creating `colorBackground` variable, you could directly use `android.R.attr.colorBackground` in here

2023-04-10 17:01 UTC, PratyushSingh07 commented
I have done the required changes @jawidMuhammadi

2023-05-03 19:39 UTC, PratyushSingh07 commented
do review this long pending PR as well @jawidMuhammadi

2023-05-03 20:46 UTC, jawidMuhammadi approved these changes

2023-05-03 20:47 UTC, merged