Modified the response body of http exception and added mock stub
openMF/self-service-app pull request #1978
Opened 2023-03-14 06:37 UTC by NiranjanNlc

Fixes #1968 and #1977

 
![image](https://user-images.githubusercontent.com/25600880/224916198-6120dd6e-1876-499e-b9ab-baa6d3e69891.png)

![image](https://user-images.githubusercontent.com/25600880/224916083-6676b271-0225-43e5-ade8-28ef407f0214.png)

2023-03-14 06:47 UTC, NiranjanNlc commented
hey @jawidMuhammadi  , would you please review this PR and suggest any changes ?

2023-03-15 10:42 UTC, jawidMuhammadi requested changes

2023-03-15 10:42 UTC, jawidMuhammadi commented on app/src/commonTest/java/org/mifos/mobile/RetrofitUtils.kt
> +    private fun getResponseForError(errorCode: Int, message : String ): Response<Any> {
The method name is self-explanatory enough, you could remove the comment.

2023-03-15 10:42 UTC, jawidMuhammadi commented on app/src/commonTest/java/org/mifos/mobile/RetrofitUtils.kt
>      fun get401Exception(): Exception {
Remove this and the `get404Exception` method and directly use the `getResponseForError` method.

2023-03-15 10:42 UTC, jawidMuhammadi commented on app/src/test/java/org/mifos/mobile/UpdatePasswordPresenterTest.kt
> +        Mockito.`when`(preferencesHelper?.userName).thenReturn("username") // username is required to update authentication token
Remove the comment, please

2023-03-15 14:16 UTC, NiranjanNlc commented
hey @jawidMuhammadi , i have made the necessary changes

2023-03-16 11:00 UTC, jawidMuhammadi approved these changes
LTMG! 👏

2023-03-16 11:00 UTC, merged