Removed Toast message
openMF/self-service-app pull request #1985
Opened 2023-03-14 19:44 UTC by lonewolf2208

Fixed #1983 

https://user-images.githubusercontent.com/72886809/225119080-3d31d815-f2fb-48c7-b2c9-7daafe927dc9.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2023-03-15 21:16 UTC, lonewolf2208 commented
Good day @jawidMuhammadi , can you review this PR

2023-03-16 11:14 UTC, jawidMuhammadi requested changes
Please follow[ these guidelines](https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide) for git commit and pull requests in your future contributions. For now, modifying the PR title should be enough.

2023-03-17 16:38 UTC, lonewolf2208 commented
> Please follow[ these guidelines](https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide) for git commit and pull requests in your future contributions. For now, modifying the PR title should be enough.
Sure will follow the guideline from further on . Is this correct now ?

2023-03-17 18:28 UTC, jawidMuhammadi approved these changes

2023-03-17 18:28 UTC, merged