Nullable View receiver in HomeFragment & HomeOldFragment causing issue #1956
openMF/self-service-app pull request #2018
Opened 2023-03-19 01:42 UTC by oyehanif

Fixes #1956 

Nullable View receiver in HomeFragment & HomeOldFragment causing issue.

2023-03-22 12:29 UTC, jawidMuhammadi requested changes
Squash your commits and follow the commit and PR template styles, please

2023-03-22 12:29 UTC, jawidMuhammadi commented on app/src/main/res/values/strings.xml
> +    <string name="TXT_PRODUCT_ERROR">Please Select Product Id</string>
Change this line of code to:
`  <string name="select_product_id">Please select product Id</string>`

2023-08-19 09:05 UTC, PratyushSingh07 commented
This issue no longer exists and hence can be pulled down

2023-08-19 14:26 UTC, PratyushSingh07 commented
No such issue exists anymore, this can be pulled down @therajanmaurya

2023-08-19 14:34 UTC, closed without merging