feat: Implement Crashlytics
openMF/self-service-app pull request #210
Opened 2017-03-18 13:57 UTC by dilpreet96

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2017-03-20 21:54 UTC, therajanmaurya requested changes

2017-03-20 21:54 UTC, therajanmaurya commented on app/src/main/AndroidManifest.xml
> +            android:value="8dbc177cd5391a21947da95f2aa9208f33cd45f4" />
Put this key to https://github.com/openMF/self-service-app/blob/development/app/src/debug/res/values/google_maps_api.xml and Make the file name `google_maps_api.xml` -> `api_keys.xml`, In both debug and release.

2017-03-21 06:26 UTC, dilpreet96 commented
@therajanmaurya on placing the keys in debug and release , gralde was throwing error on build 

`Error:Execution failed for task ':app:fabricGenerateResourcesDebug'. Crashlytics Developer Tools error.`

On searching for this I came to know that fabric does not allow string references and then followed their official guide for placing the api key 
https://docs.fabric.io/android/fabric/settings/working-in-teams.html#android-projects

2017-03-22 09:14 UTC, therajanmaurya commented
ok, You have to change release api key file name too.

2017-03-22 12:09 UTC, dilpreet96 commented
@therajanmaurya ,if I am getting you right then, both debug and release xml are named as api_key.xml , please have a look

2017-03-23 16:25 UTC, merged