migrated activities from butterknife to viewbinding
openMF/self-service-app pull request #2144
Opened 2023-05-18 20:08 UTC by PratyushSingh07

Migrated Activities from  butterknife to viewbinding as part of GSoC 23

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2023-05-19 05:12 UTC, gururani-abhishek requested changes
Please have an overall look at all the activities and if you find instances of Kotlin Synthetics then replace them with ViewBinding.

2023-05-19 05:12 UTC, gururani-abhishek commented on app/src/main/java/org/mifos/mobile/ui/activities/HomeActivity.kt
> +import kotlinx.android.synthetic.main.toolbar.view.*
IDE automatically added Kotlin Synthetic library due to some workaround. We need to get rid of this.

2023-05-19 05:12 UTC, gururani-abhishek commented on app/src/main/java/org/mifos/mobile/ui/activities/HomeActivity.kt
> +        setSupportActionBar(binding.root.toolbar)
The workaround that introduced above Kotlin synthetic lib is here. "toolbar" is the name of layout, not it's ID, hence when you're accessing it using "binding.root.toolbar" Kotlin Synthetic is getting used, what we can do instead is : 
1. in HomeActivity.xml give the included layout "toolbar" some id
2. then access it using that ID, something like this -> binding.idGivenToToolbar.root(do double-check on this, I'm not 100% sure)

this type of workaround is expected with included layouts read more here -> [Stackoverflow](https://stackoverflow.com/a/58730128)

2023-05-19 05:12 UTC, gururani-abhishek commented on app/src/main/java/org/mifos/mobile/ui/activities/EditUserDetailActivity.kt
> +        setSupportActionBar(binding.root.toolbar)
This works perfectly fine but just a suggestion -> 
Instead of calling setSupportActionBar() right from our activities, how bout overriding setContentView(view : View?) {...setSupportActionBar()...} in our BaseActivity()?[ reference](https://github.com/openMF/mifos-mobile/pull/2143/commits/ea586368a7cb09fc982260606f0a6fc8ceeb9169#diff-061eaf0e6e045746e15221e289cc4e5623af2fa6e9e66c12818794c97a48a10b)
This way we can save ourselves from writing extra code, plus similar feature was already there in BaseActivity() while we were using Butterknife. Still it's just a suggestion, totally your call.

2023-05-19 05:12 UTC, gururani-abhishek commented on app/src/main/java/org/mifos/mobile/ui/activities/HomeActivity.kt
> +        showBackButton()
Why are we showing a backButton in HomeActivity? It'll overlap navigation drawer icon with the backButton.

<img width="353" alt="Screenshot 2023-05-19 at 09 56 26" src="https://github.com/openMF/mifos-mobile/assets/59947871/2fe8fe72-11c8-4bd7-91ce-3aee76330b69">

2023-05-19 05:12 UTC, gururani-abhishek commented on app/src/main/java/org/mifos/mobile/ui/activities/LoginActivity.kt
>  import butterknife.OnTouch
Please remove this unused import.

2023-05-19 05:12 UTC, gururani-abhishek commented on app/src/main/java/org/mifos/mobile/ui/activities/LoginActivity.kt
>          dismissSoftKeyboardOnBkgTap(nsv_background)
"nsv_background" is being accessed using Kotlin Synthetic, use binding here. And remove Kotlin Synthetic Library from the imports too.

2023-05-19 05:12 UTC, gururani-abhishek commented on app/src/main/java/org/mifos/mobile/ui/activities/SavingsAccountApplicationActivity.kt
> +import org.mifos.mobile.databinding.ActivityNotificationBinding
remove this unused import please

2023-05-19 05:18 UTC, gururani-abhishek commented on app/src/main/java/org/mifos/mobile/ui/activities/HomeActivity.kt
>          drawerUserImage = ButterKnife.findById(headerView, R.id.user_image_round)
Use of ButterKnife!! remove it please.

2023-05-20 18:54 UTC, gururani-abhishek commented on app/src/main/java/org/mifos/mobile/ui/activities/EditUserDetailActivity.kt
>  import butterknife.ButterKnife
Butterknife import, remove this and its usage(if any!!)

2023-05-22 16:50 UTC, PratyushSingh07 commented
Hey @jawidMuhammadi , do have a look at this PR , I have linked the issue to this PR and also changed the PR description 
Do let me know if there are other changes that needs to be done

2023-05-22 21:21 UTC, jawidMuhammadi approved these changes
LGTM!

2023-05-22 21:21 UTC, merged