fix #2142: migrated savings,update,user and loan fragments to viewbinding
openMF/self-service-app pull request #2148
Opened 2023-05-27 10:34 UTC by PratyushSingh07

Fixes #2142

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2023-05-27 11:50 UTC, PratyushSingh07 commented
Hey @gururani-abhishek do review this

2023-05-29 23:16 UTC, gururani-abhishek requested changes
Please have a look at these requested changes, rest it looks good to me. Good Job buddy!!

2023-05-29 23:16 UTC, gururani-abhishek commented on app/src/main/java/org/mifos/mobile/ui/fragments/SavingsAccountApplicationFragment.kt
> +        payload.productId = productIdList.indexOf(binding.productIdField?.text.toString())
In "binding.productIdField?.text" please remove the unnecessary safe-call.

2023-05-29 23:16 UTC, gururani-abhishek commented on app/src/main/java/org/mifos/mobile/ui/fragments/SavingsMakeTransferFragment.kt
updateDetails() can be made private

2023-05-29 23:16 UTC, gururani-abhishek commented on app/src/main/java/org/mifos/mobile/ui/fragments/SavingsMakeTransferFragment.kt
> +        binding.llMakeTransfer?.visibility = View.GONE
In "binding.llMakeTransfer?.visibility" please remove the unnecessary safe-call.

2023-05-29 23:16 UTC, gururani-abhishek commented on app/src/main/java/org/mifos/mobile/ui/fragments/SavingsMakeTransferFragment.kt
> +        binding.payToFieldWrapper?.isEnabled = false
safe-call can be removed here as well, "binding.payToFieldWrapper?.isEnabled"

2023-05-29 23:16 UTC, gururani-abhishek commented on app/src/main/java/org/mifos/mobile/ui/fragments/UpdatePasswordFragment.kt
> +    override fun onDestroy() {
This onDestroy() callback is redundant and can be removed.

2023-05-30 05:07 UTC, PratyushSingh07 commented
made the changes that were asked in the review , do review this from your side as well @jawidMuhammadi

2023-05-31 21:52 UTC, jawidMuhammadi approved these changes
LGTM! :)

2023-05-31 21:53 UTC, merged