feat:UI enhancement by Sweet alert dialog box instead of snackbar in charges activity when there is no internet connection
openMF/self-service-app pull request #216
Opened 2017-03-21 10:15 UTC by itsamitgoel

Sweet alert dialog box instead of snackbar when there is no internet
connection in  charges activity

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2017-03-21 12:58 UTC, itsamitgoel commented
![screenshot_2017-03-11-23-46-09-774_org mifos selfserviceapp](https://cloud.githubusercontent.com/assets/16203080/24148272/147a9cba-0e64-11e7-9324-24c989c13c64.png)

2017-04-01 05:14 UTC, therajanmaurya requested changes

2017-04-01 05:14 UTC, therajanmaurya commented on app/build.gradle
> +    compile 'cn.pedant.sweetalert:library:1.3'
We can not use, External Library for Material Dialog.  Use this class https://github.com/openMF/self-service-app/blob/development/app/src/main/java/org/mifos/selfserviceapp/utils/MaterialDialog.java

2017-07-27 09:50 UTC, dilpreet96 commented
Using external library for this purpose is not required.

2017-07-27 09:50 UTC, closed without merging