fix : no filter selected works properly in accounts fragment
openMF/self-service-app pull request #2188
Opened 2023-06-26 12:31 UTC by ayush290104

fix #1397 <on not selecting any filter account fragment now shows full list earlier it used to show empty list.>
before fix
https://github.com/openMF/mifos-mobile/assets/116818222/ec7f7395-9a28-462e-a9e8-e8e94063ef56
after fix

https://github.com/openMF/mifos-mobile/assets/116818222/92a09d8e-9c04-4d71-90b9-466e65c4801b

2023-06-27 12:41 UTC, ayush290104 commented
@PratyushSingh07 sir can you see this once

2023-06-27 13:26 UTC, PratyushSingh07 commented
LGMT!!

2023-06-29 04:29 UTC, ayush290104 commented
Hey @jawidMuhammadi can you please merge it.

2023-06-29 09:12 UTC, jawidMuhammadi requested changes

2023-06-29 09:12 UTC, jawidMuhammadi commented on app/src/main/java/org/mifos/mobile/ui/fragments/AccountsFragment.kt
> +        }
You could simply do this:
```
   if (accountsPresenter?.getCheckedStatus(statusModelList) != null && accountsPresenter != nul) {
        if (accountsPresenter?.getCheckedStatus(statusModelList)?.isNotEmpty() == true) {
            for (status in accountsPresenter?.getCheckedStatus(statusModelList)!!) {
                accountsPresenter?.getFilteredSavingsAccount(
                    savingAccounts,
                    status,
                )?.let { filteredSavings.addAll(it) }
            }
        } else {
            savingAccounts?.forEach {
                filteredSavings.add(it)
            }
        }
    }
```

And also your **code needs to be reformated**, use Cmd+Option+L (on Mac) or Ctrl+Alt+L (on Windows and Linux)

2023-07-03 17:22 UTC, PratyushSingh07 commented
hey @ayush290104 can you make the necessary changes so that we can merge it?

2023-07-05 05:22 UTC, ayush290104 commented
@PratyushSingh07 I am confused as i did changes on my local system but how to edit my pr or should i open a new pr

2023-07-05 05:39 UTC, closed without merging