Fix #2432: fixed about us landscape orientation ui
openMF/self-service-app pull request #2437
Opened 2023-11-14 16:42 UTC by keshriAyushh

https://github.com/openMF/mifos-mobile/assets/90385832/5e01a069-75b7-4c03-8625-a97be0af65e2

Fixes #2432

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2023-11-14 16:51 UTC, PratyushSingh07 requested changes

2023-11-14 16:51 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/about/AboutUsScreen.kt
> +
remove these extra spaces

2023-11-14 16:51 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/about/AboutUsFragment.kt
> +    @SuppressLint("UnusedMaterial3ScaffoldPaddingParameter")
no need to add this , you can remove scaffold from this fragment

2023-11-14 18:41 UTC, PratyushSingh07 commented
please squash your commits into one . You can follow the guide [here](https://www.git-tower.com/learn/git/faq/git-squash)

2023-12-26 08:16 UTC, neeldoshii commented
@PratyushSingh07 can I work on this and complete the PR so the issue can be fixed and PR be closed. This issue and PR has been staled for a month can I work on it?

2023-12-26 08:22 UTC, PratyushSingh07 commented
This PR is complete @neeldoshii

2023-12-28 16:21 UTC, merged