Fixed Feat: Implement Shimmer while user details are being loaded
openMF/self-service-app pull request #2443
Opened 2023-11-19 10:49 UTC by kmanikanta335

Fixes #2412 

 Screenshots of UI changes.

https://github.com/openMF/mifos-mobile/assets/118070186/747c140f-e653-451d-ad05-4a485c8f5d9c 

https://github.com/openMF/mifos-mobile/assets/118070186/36a2e396-25ed-4254-b548-64bd584c8b9d

Please make sure these boxes are checked before submitting your pull request - thanks!

- ✅  Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- ✅  Run the unit tests with `./gradlew check` to make sure you didn't break anything

- ✅  If you have multiple commits please combine them into one commit by squashing them.

2023-11-19 10:50 UTC, kmanikanta335 commented
@PratyushSingh07 pls review it

2023-11-20 15:53 UTC, PratyushSingh07 requested changes
Also make sure to follow the commit guidelines

2023-11-20 15:53 UTC, PratyushSingh07 commented on app/build.gradle
> +    implementation 'com.facebook.shimmer:shimmer:0.5.0'
add the version to ext block and add a comment that will describe the dependency

2023-11-20 15:53 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/fragments/HomeOldFragment.kt
> +                        binding.shimmerViewContainer.visibility = View.INVISIBLE
these 3 can be put into a function

2023-11-20 18:06 UTC, PratyushSingh07 requested changes

2023-11-20 18:06 UTC, PratyushSingh07 commented on app/build.gradle
> +    // Shimmer effect dependencies
`Shimmer Effect` should be enough

2023-11-20 18:06 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/fragments/HomeOldFragment.kt
> +     */
we dont need this , the name of the function is self explanatory

2023-11-20 18:06 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/fragments/RecentTransactionsFragment.kt
> +                    Toast.makeText(context,"hello",Toast.LENGTH_SHORT).show()
dont push changes of other issues in this one

2023-11-21 12:37 UTC, PratyushSingh07 approved these changes
LGTM

2023-11-22 16:00 UTC, PratyushSingh07 commented
make sure to change the commit message @kmanikanta335

2023-11-22 16:33 UTC, kmanikanta335 commented
@PratyushSingh07 what should I change it to

2023-11-22 17:32 UTC, PratyushSingh07 commented
> @PratyushSingh07 what should I change it to

just follow the guidelines

2023-11-26 04:59 UTC, kmanikanta335 commented
@PratyushSingh07 when will it gets merged

2023-11-26 09:52 UTC, PratyushSingh07 commented
> @PratyushSingh07 when will it gets merged

You still haven't followed the commit guidelines. It will be merged only after the admins approval

2023-11-26 12:48 UTC, kmanikanta335 commented
@PratyushSingh07 i hope now its fine

2023-12-28 16:25 UTC, therajanmaurya commented
Please resolve the conflicts.

2024-01-02 15:12 UTC, kmanikanta335 commented
@therajanmaurya i hope now it fine

2024-01-02 16:26 UTC, PratyushSingh07 requested changes
Format your code with `ctrl+shift+L` if  you haven't already. Also I will be converting this PR to draft . You can make it ready for review after you have implemented the changes that i requested

2024-01-02 16:26 UTC, PratyushSingh07 commented on app/build.gradle
> +    implementation 'com.facebook.shimmer:shimmer:0.5.0'
you still havent implemented this change @kmanikanta335

2024-01-02 19:30 UTC, PratyushSingh07 commented
@kmanikanta335 squash your commits and make sure that your final commit follow contribution guidelines

2024-08-31 16:05 UTC, closed without merging