Fixed #2442 :When Recent Transactions is opened without connection of internet…
openMF/self-service-app pull request #2444
Opened 2023-11-25 12:46 UTC by kmanikanta335

Fixes #2442 

Screenshots of UI changes.

https://github.com/openMF/mifos-mobile/assets/118070186/97667b8b-2cf0-44f8-89b6-48f550635820

Please make sure these boxes are checked before submitting your pull request - thanks!

- ✅  Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- ✅  Run the unit tests with `./gradlew check` to make sure you didn't break anything

- ✅  If you have multiple commits please combine them into one commit by squashing them.

2023-11-25 12:47 UTC, kmanikanta335 commented
@PratyushSingh07 pls review it

2023-11-29 20:10 UTC, PratyushSingh07 commented
LGTM , we can merge this @therajanmaurya

2023-12-28 16:26 UTC, therajanmaurya commented
Resolve the conflicts.

2023-12-29 05:37 UTC, antima123-bit commented
can i take solve this issue @PratayushSingh07

2023-12-29 05:44 UTC, PratyushSingh07 commented
> can i take solve this issue @PratayushSingh07

This pull request currently contains some merge conflicts. Once the author, @kmanikanta335 , resolves these conflicts, we'll proceed with merging it into our codebase

2023-12-31 16:07 UTC, kmanikanta335 commented
@therajanmaurya I resolved merge conflicts

2024-01-02 07:08 UTC, PratyushSingh07 requested changes
Hi @kmanikanta335 , I noticed you made some changes to the code by adding two new blank lines which is a bit weird because when you remove those 2 lines you will get the orignal code

2024-01-02 07:08 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/fragments/RecentTransactionsFragment.kt
> +
this is the 1st blank space

2024-01-02 07:08 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/viewModels/RecentTransactionViewModel.kt
> +
this is the 2nd blank space

2024-01-02 14:41 UTC, closed without merging