About us refactor
openMF/self-service-app pull request #2481
Opened 2024-01-09 05:01 UTC by NiranjanNlc

Fixes #2472 
 
Same UI shown after refactoring 
![Screenshot_2024-01-09-10-40-06-758_org mifos mobile](https://github.com/openMF/mifos-mobile/assets/25600880/d55acd0a-4ac7-4a60-94ae-dacc1e8bfa22)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2024-01-09 05:20 UTC, NiranjanNlc commented
@PratyushSingh07

2024-01-09 08:01 UTC, PratyushSingh07 requested changes
change your PR & commit message to something that follows our guidelines. For this you can refer CONTRIBUTION.md . Also format your code if you havent already. I am converting this PR to draft. You can make it readu for review after you have implemented the changes

2024-01-09 08:01 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/repositories/AboutUsRepository.kt
> +    fun getAboutUsItems(): List<AboutUsItem>
use kotlin flows

2024-01-09 08:01 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/repositories/AboutUsRepositoryImpl.kt
> +    override fun getAboutUsItems(): List<AboutUsItem> {
return Flow<List<AboutUsItem>>

2024-01-09 08:01 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/about/AboutUsScreen.kt
> +import androidx.compose.ui.tooling.preview.PreviewParameter
do we need this import?

2024-01-09 08:01 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/about/AboutUsScreen.kt
> + AboutUsScreen(viewModel = viewModel())
revert to `AboutUsViewModel` . I dont think we needed to change this

2024-01-09 08:01 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/about/AboutUsViewModel.kt
> +    private val aboutUsRepository: AboutUsRepository
replace this with `private val aboutUsRepositoryImp: AboutUsRepository`

2024-01-09 11:37 UTC, NiranjanNlc commented on app/src/main/java/org/mifos/mobile/ui/about/AboutUsScreen.kt
> + AboutUsScreen(viewModel = viewModel())
since  we have added the AboutUsRepository in the constructor of viewmodal ,  we need to make a change  to adapt this

2024-01-09 11:58 UTC, NiranjanNlc reviewed
all changes are done

2024-01-09 11:58 UTC, NiranjanNlc commented on app/src/main/java/org/mifos/mobile/repositories/AboutUsRepository.kt
> +    fun getAboutUsItems(): List<AboutUsItem>
done

2024-01-09 11:58 UTC, NiranjanNlc commented on app/src/main/java/org/mifos/mobile/repositories/AboutUsRepositoryImpl.kt
> +    override fun getAboutUsItems(): List<AboutUsItem> {
done

2024-01-09 11:58 UTC, NiranjanNlc commented on app/src/main/java/org/mifos/mobile/ui/about/AboutUsScreen.kt
> +import androidx.compose.ui.tooling.preview.PreviewParameter
import optimized

2024-01-09 11:58 UTC, NiranjanNlc commented on app/src/main/java/org/mifos/mobile/ui/about/AboutUsViewModel.kt
> +    private val aboutUsRepository: AboutUsRepository
done

2024-01-09 12:08 UTC, NiranjanNlc commented
Implemented the changes as you suggested @PratyushSingh07

2024-01-28 16:15 UTC, closed without merging

2024-01-28 16:15 UTC, therajanmaurya commented
We are focusing on jetpack compose implementation, this will be useless to implement you are free to send PR for converting xml to compose.

2024-01-29 00:28 UTC, NiranjanNlc commented
> We are focusing on jetpack compose implementation, this will be useless to implement you are free to send PR for converting xml to compose.

Thanks @therajanmaurya for feedback.