feat: Compose View for Help Screen
openMF/self-service-app pull request #2489
Opened 2024-01-23 07:38 UTC by AvneetSingh2001

Fixes #2447 

Screen Recording (Light Mode):
https://github.com/openMF/mifos-mobile/assets/77102514/392d4c49-7b60-49ae-87b3-e284c2027741

Screenshot (Dark Mode) 
![screenshot_20240123_120801_mifos_mobile_720](https://github.com/openMF/mifos-mobile/assets/77102514/4eacd776-199f-4b04-9f0d-0615212ef9f0)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2024-01-23 14:06 UTC, therajanmaurya commented
Thanks for the PR! Let me review

2024-01-23 14:11 UTC, therajanmaurya requested changes

2024-01-23 14:11 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobile/ui/help/HelpScreen.kt
> +        if (!faqArrayList.isNullOrEmpty() && faqArrayList.isNotEmpty()) {
`!faqArrayList.isNullOrEmpty()` is enough, don't ned to add `faqArrayList.isNotEmpty()`

2024-01-23 14:11 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobile/ui/help/HelpTopBar.kt
> +fun HelpTopBar(
Add new module called `ui` and make this generic and move there.

2024-01-23 14:11 UTC, therajanmaurya commented on core/src/main/java/org/mifos/mobile/core/ui/component/EmptyDataView.kt
> +fun EmptyDataView(
Move in new module `ui` as suggested.

2024-01-23 14:11 UTC, therajanmaurya commented on core/src/main/java/org/mifos/mobile/core/ui/component/MifosSearchTextField.kt
> +fun MifosSearchTextField(
move it to `ui` module as suggested.

2024-01-23 14:11 UTC, therajanmaurya commented on core/src/main/java/org/mifos/mobile/core/ui/component/MifosTextButtonWithTopDrawable.kt
> +fun MifosTextButtonWithTopDrawable(
move it to ui module as suggested.

2024-01-23 14:11 UTC, therajanmaurya commented
@AvneetSingh2001 Please make suggested changes.

2024-01-23 14:23 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/help/HelpTopBar.kt
> +fun HelpTopBar(
Hey @AvneetSingh2001 no need to create a new module. You can just rename `core` to `ui`

2024-01-23 15:13 UTC, PratyushSingh07 commented
Hey @AvneetSingh2001 I went through the recording that you have attached. There are a couple of things that I would like to point out:
- text size of the query in search bar looks big
- after you change the orientation (landscape to portrait and vice versa) I saw that the rest of the questionnaire lost their visibility. Is it actually a bug or is it just the screen recording? I am attaching the screenshot below
https://github.com/openMF/mifos-mobile/assets/90026952/0233a512-4b96-4ea0-9623-9f462b375511

2024-01-23 16:01 UTC, AvneetSingh2001 commented
@therajanmaurya Thanks for reviewing it, I will make the necessary changes.

@PratyushSingh07, thanks for mentioning the bugs, Will make the search bar text smaller.  Additionally for the second point that you have mentioned, Its not a bug, You can see the "qr" is already searched in search text field, which is retained over the screen orientations.

2024-01-23 16:05 UTC, PratyushSingh07 commented
> @PratyushSingh07, thanks for mentioning the bugs, Will make the search bar text smaller. Additionally for the second point that you have mentioned, Its not a bug, You can see the "qr" is already searched in search text field, which is retained over the screen orientations.

Ohhh I'm sorry, I had missed that

2024-01-23 16:52 UTC, AvneetSingh2001 commented
@therajanmaurya @PratyushSingh07 , I have made the necessary changes.

2024-01-23 17:33 UTC, therajanmaurya commented
> @therajanmaurya Thanks for reviewing it, I will make the necessary changes.
> 
> @PratyushSingh07, thanks for mentioning the bugs, Will make the search bar text smaller. Additionally for the second point that you have mentioned, Its not a bug, You can see the "qr" is already searched in search text field, which is retained over the screen orientations.

Always remember follow material guidelines.

2024-01-23 17:35 UTC, PratyushSingh07 commented
@AvneetSingh2001 please squash your commits and follow our contribution guidelines . your commit message should have been 
`refactor #2447: migrated help screen to compose`

2024-01-23 18:10 UTC, AvneetSingh2001 commented
@PratyushSingh07  thanks for correcting my commit, I have squashed the commits, have a look.

2024-01-23 18:20 UTC, PratyushSingh07 commented
Looks neat @AvneetSingh2001 . Great job !!

2024-01-23 18:23 UTC, AvneetSingh2001 commented
@PratyushSingh07 Should i also delete files that were used in XML view like adapter, they are now redundant as they are not being used anywhere else.

2024-01-23 18:27 UTC, PratyushSingh07 commented
> @PratyushSingh07 Should i also delete files that were used in XML view like adapter, they are now redundant as they are not being used anywhere else.

yes you can but be 100% sure before deleting them :) . And yes after this you will have to squash your commits again

2024-01-23 18:54 UTC, AvneetSingh2001 commented
@PratyushSingh07 done. Thanks a lot for your support :)

2024-01-23 19:06 UTC, therajanmaurya commented
> @PratyushSingh07 done. Thanks a lot for your support :). Are we open to more compose migrations?

We want to migrate whole project in compose, You are welcome to send a PR. let me know when you are done with changes.

2024-01-23 19:10 UTC, AvneetSingh2001 commented
@therajanmaurya , the tasks of this PR is completed. 
Looking forward to more migrations.  Thanks :)

2024-01-28 16:06 UTC, therajanmaurya commented
@AvneetSingh2001 can you please fix git conflicts ?

2024-01-30 07:23 UTC, AvneetSingh2001 commented
Hey @therajanmaurya , I have solved the conflicts, Do i need to squash here, can you please check.
Thanks.

2024-01-30 07:51 UTC, AvneetSingh2001 commented
@therajanmaurya   @PratyushSingh07  , i am not able to squash the commit after merging, is it okay or do i need to find some way to squash?

2024-01-30 07:54 UTC, PratyushSingh07 commented
This happens whenever you try to merge a branch into another branch. One way to fix this is by cherry picking. You can try it out if you want as it can be a life saver in some open source projects. But if you find it cumbersome then Rajan can do it at his end as well

2024-01-30 12:47 UTC, AvneetSingh2001 commented
ok, let me try the mentioned option then.
Thanks for your input @PratyushSingh07  :)

2024-01-31 01:48 UTC, therajanmaurya approved these changes

2024-01-31 01:48 UTC, merged