Saving account transaction ui improve
openMF/self-service-app pull request #252
Opened 2017-03-25 20:49 UTC by vladimirfomene

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2017-03-25 20:51 UTC, vladimirfomene commented
@therajanmaurya please have a look at this PR.

2017-04-01 05:43 UTC, therajanmaurya requested changes

2017-04-01 05:43 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/ui/fragments/SavingAccountsTransactionFragment.java
> +        intent.setData(Uri.parse("tel:" + getString(R.string.help_line_number)));
This is not the part of this PR and It is already implemented in #219. Remove this and Please add screenshot for your changes in UI.

2017-04-01 05:45 UTC, therajanmaurya commented
@vladimirfomene Please squash your commits.

2017-07-26 16:21 UTC, closed without merging