fix: app crash on clicking submit loanbutton in apply for loan fragment
openMF/self-service-app pull request #253
Opened 2017-03-25 21:47 UTC by itsamitgoel

say user is in home screen and then losses his internet connection. then going to Apply for Loan fragment and clicking SUBMIT LOAN button causes the app to crash. fixed it .Instead it now shows a snackbar with "failed to load template" message.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2017-03-30 21:02 UTC, itsamitgoel commented
![screenshot_2017-03-31-02-29-07-854_org mifos selfserviceapp](https://cloud.githubusercontent.com/assets/16203080/24526020/37c0e1cc-15ba-11e7-9f59-97c63621a1de.png)

2017-03-30 21:03 UTC, itsamitgoel commented
Fixes #220

2017-04-01 05:49 UTC, therajanmaurya requested changes

2017-04-01 05:49 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/ui/fragments/LoanApplicationFragment.java
> +            showError("failed to load template");
This feature needs more improvement but for now change SnackBar message to strings.xml string's `no_internet_connection`

2017-07-27 09:18 UTC, dilpreet96 commented
Issue fixed in #300

2017-07-27 09:18 UTC, closed without merging