safe way to collect flows from android UI
openMF/self-service-app pull request #2550
Opened 2024-03-26 12:00 UTC by MuindiStephen

The safest way to collecting flows from UI eg. HomeActivity

repeatOnLifecycle is a suspend function that takes a [Lifecycle.State](https://developer.android.com/reference/android/arch/lifecycle/Lifecycle.State) as a parameter which is used to automatically create and launch a new coroutine with the block passed to it when the lifecycle reaches that state, and cancel the ongoing coroutine that’s executing the block when the lifecycle falls below the state

2024-03-26 12:02 UTC, MuindiStephen commented on app/src/main/java/org/mifos/mobile/utils/UserDetailUiState.kt
> +import org.mifos.mobile.ui.user_profile.UserDetails
remove unused imports

2024-03-26 12:02 UTC, MuindiStephen commented on app/src/main/java/org/mifos/mobile/utils/UserDetailUiState.kt
> +
Ignore this class, just that its another to declare ui state

2024-04-07 22:32 UTC, therajanmaurya requested changes

2024-04-07 22:32 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobile/utils/UserDetailUiState.kt
> + */
remove this unused code block.

2024-04-08 11:50 UTC, MuindiStephen commented on app/src/main/java/org/mifos/mobile/utils/UserDetailUiState.kt
> + */
> remove this unused code block.

Yes. Looking into that.

2024-04-08 11:55 UTC, MuindiStephen commented on app/src/main/java/org/mifos/mobile/utils/UserDetailUiState.kt
>  sealed class UserDetailUiState {
To be removed, since unused block of code stmt.

2024-08-31 16:00 UTC, therajanmaurya commented
We are not using fragments anymore.

2024-08-31 16:00 UTC, closed without merging