refactor: Migration of Loan Application screen to compose
openMF/self-service-app pull request #2571
Opened 2024-04-21 12:18 UTC by AvneetSingh2001

Fixes #2546 

Please Add Screenshots If there are any UI changes.
| XML Screen (before)                                                                                               |  Compose Screen (Now)                                                                                            | 
|-------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------|
| https://github.com/openMF/mifos-mobile/assets/77102514/0c1d054d-2048-462a-9a7e-d4786b3dc90e | https://github.com/openMF/mifos-mobile/assets/77102514/0dba877d-046b-4470-b4a3-2153b418e6d0 |

2024-05-06 16:47 UTC, PratyushSingh07 requested changes

2024-05-06 16:47 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/loan_account_application/LoanApplicationContent.kt
> +        OutlinedTextField(
MifosOutlinedTextField

2024-05-06 16:47 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/loan_account_application/LoanApplicationContent.kt
> +                if(uiData.selectedLoanProduct.isNullOrBlank()) {
replace with when

2024-05-06 16:47 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/loan_account_application/LoanApplicationContent.kt
> +                        val formattedDate = SimpleDateFormat("dd-MM-yyyy", Locale.getDefault()).format(timeInMillis)
move to utility function

2024-05-06 16:47 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/loan_account_application/LoanApplicationContent.kt
> +                ) { Text("OK") }
string res

2024-05-06 16:47 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/loan_account_application/LoanApplicationContent.kt
> +                ) { Text("Cancel") }
...

2024-05-06 16:47 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/loan_account_application/LoanApplicationFragment.kt
> +                        viewModel = viewModel,
hilt viewmodel in  compose

2024-05-06 16:47 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/loan_account_application/LoanApplicationScreen.kt
> +}
make a generic composable

2024-06-01 04:40 UTC, Aditya-gupta99 commented
LGTM

2024-06-02 23:56 UTC, merged