migrate transfer process screen to compose screen #2583
openMF/self-service-app pull request #2585
Opened 2024-05-13 06:52 UTC by Saifuddin53

Fixes #2583 

Please Add Screenshots If there are any UI changes.
<html>
<body>

XML Screen (before) | Compose Screen (Now)
-- | --
![before](https://github.com/openMF/mifos-mobile/assets/112172255/fb59f0de-86ed-4f6e-9147-e0a0bd1be0b2) | ![after](https://github.com/openMF/mifos-mobile/assets/112172255/f466a498-10b1-489c-b736-cc5a06806d72)

<ul dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;">UI States Preview Screenshot</li></ul>
</body>
</html>

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2024-05-13 23:01 UTC, AvneetSingh2001 requested changes

2024-05-13 23:01 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/transfer_process/TransferProcessComposeFragment.kt
> +        activity?.supportFragmentManager?.popBackStack()
typo: two same lines

2024-05-13 23:01 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/transfer_process/TransferProcessComposeFragment.kt
> +                            viewModel.makeTransfer(payload)
make this function of viewModel in the compose screen `TransferProcessScreen`,  as we have the instance of viewModel there

2024-05-13 23:01 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/transfer_process/TransferProcessComposeFragment.kt
> +    private var transferType: TransferType? = null
move this to viewModel as well

2024-05-13 23:01 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/transfer_process/TransferProcessViewModel.kt
> +    fun makeTransfer(payload: TransferPayload) {
use proper spacing between lines, and beautify text in Android studio before any commit

2024-05-13 23:02 UTC, AvneetSingh2001 commented
@Saifuddin53  requested some change, please update the code accordingly. Also can you please add screen recording as well

2024-05-14 16:36 UTC, AvneetSingh2001 commented
@Saifuddin53 , can you check why are we getting HTTP 400 response for this?

2024-05-14 16:47 UTC, Saifuddin53 commented
I think it's a server side error

2024-05-14 16:49 UTC, AvneetSingh2001 commented
can you paste the logs about the error here

2024-05-15 03:17 UTC, Saifuddin53 commented
<img width="767" alt="Screenshot 2024-05-15 084635" src="https://github.com/openMF/mifos-mobile/assets/112172255/3f5f0a58-8231-4068-bf02-4ffd9694d46a">

2024-05-15 04:12 UTC, Saifuddin53 commented
The same error is coming in our view-based screen. It would be solved when we migrate our previous screen which is SavingsMakeTransferFragment as it is passing **null** for now

2024-05-15 04:15 UTC, Saifuddin53 commented
https://github.com/openMF/mifos-mobile/assets/112172255/5df044c6-40c2-4fa7-93b6-b8301b0f8dc5

2024-05-15 16:20 UTC, Saifuddin53 commented
<img width="671" alt="Screenshot 2024-05-15 214738" src="https://github.com/openMF/mifos-mobile/assets/112172255/6837c080-1acb-4ed4-a0cd-da3604aa4fce">
@AvneetSingh2001 here the showSavingsAccountTemplate function is not able to fetch the accounts from the AccountOptions list

2024-05-15 16:50 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/transfer_process/TransferProcessComposeFragment.kt
> +        activity?.supportFragmentManager?.popBackStack()
same lines still

2024-05-15 16:50 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/transfer_process/TransferProcessScreen.kt
> +                is TransferUiState.Initial -> {}
use Unit, 
                is TransferUiState.Initial ->  Unit

2024-05-19 08:26 UTC, itsPronay commented on app/src/main/java/org/mifos/mobile/ui/transfer_process/TransferProcessComposeFragment.kt
> +                                closeClicked()
I think replacing this with `activity?.supportFragmentManager?.popBackStack()` is a better option.

2024-05-19 08:29 UTC, itsPronay commented on app/src/main/java/org/mifos/mobile/ui/transfer_process/TransferProcessScreen.kt
> +}
generate previews

2024-06-03 06:44 UTC, Saifuddin53 commented
@AvneetSingh2001 can you please review it again

2024-06-03 07:00 UTC, itsPronay commented
@Saifuddin53 I see you have multiple commits. Please squash them

2024-06-03 07:52 UTC, itsPronay commented on app/src/main/java/org/mifos/mobile/ui/transfer_process/TransferProcessComposeFragment.kt
> +
Hide toolbar on resume

2024-06-03 08:08 UTC, itsPronay requested changes
![image](https://github.com/openMF/mifos-mobile/assets/78101731/4d41eff4-cb47-4bcd-8943-5aaaaae4154f)

fix this one as well. 
 There's an issue with the layout when the device is rotated. Only a portion of the screen remains visible, and scrolling is disabled because you're using a Column.

2024-06-03 08:11 UTC, itsPronay commented on app/src/main/java/org/mifos/mobile/ui/transfer_process/TransferProcessComposeFragment.kt
> +
and for toolbar use scaffold

2024-06-03 08:13 UTC, itsPronay commented
also please reformat your code, I believe it's ctrl + alt + L

2024-06-03 08:29 UTC, itsPronay commented on app/src/main/java/org/mifos/mobile/ui/transfer_process/TransferProcessScreen.kt
> +                                  cancel()
![image](https://github.com/openMF/mifos-mobile/assets/78101731/3e65d4ad-45f0-4c8b-a606-c7b6e618d761)
you didn't implement this snackbar.. Original (XML) one has it... add this as well

2024-06-14 19:01 UTC, merged