refactor #2587: savings make transfer migration
openMF/self-service-app pull request #2594
Opened 2024-05-19 00:35 UTC by AvneetSingh2001

Fixes #2587

2024-05-31 12:29 UTC, Aditya-gupta99 requested changes

2024-05-31 12:29 UTC, Aditya-gupta99 commented on app/src/main/java/org/mifos/mobile/ui/savings_make_transfer/SavingsMakeTransferComposeFragment.kt
> +        transferPayload.toAccountNumber = payload.payToAccount?.accountNo
Replace this with apply scope function

2024-06-01 01:36 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/savings_make_transfer/SavingsMakeTransferComposeFragment.kt
> +        transferPayload.toAccountNumber = payload.payToAccount?.accountNo
done bro

2024-06-01 04:32 UTC, Aditya-gupta99 approved these changes

2024-06-02 15:15 UTC, merged