migrate saving accounts transaction screen to compose #2588
openMF/self-service-app pull request #2596
Opened 2024-06-01 11:45 UTC by Saifuddin53

Fixes #2588 

Please Add Screenshots If there are any UI changes.

Before : 

https://github.com/openMF/mifos-mobile/assets/112172255/9f539208-9a5e-49cc-9e26-c7c9578a0fe3

After :

https://github.com/openMF/mifos-mobile/assets/112172255/0b9f7124-7f11-4d06-b2c9-d3b65b202dad

2024-06-02 06:21 UTC, AvneetSingh2001 requested changes

2024-06-02 06:21 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/savings_account_transaction/SavingAccountsTransactionScreen.kt
> +    val dialogState by viewModel.isDialogOpen.collectAsStateWithLifecycle()
why have you kept dialogstate in viewmodel?

2024-06-02 06:21 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/savings_account_transaction/SavingAccountsTransactionScreen.kt
> +    val context: Context = LocalContext.current
dont initilise it here itself, intialise in a composable where its been used.

2024-06-02 06:21 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/savings_account_transaction/SavingAccountsTransactionScreen.kt
> +    val context: Context = LocalContext.current
dont initialise it here, keep in composable where its been used.

2024-06-02 06:21 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/savings_account_transaction/SavingAccountsTransactionScreen.kt
> +    viewModel: SavingAccountsTransactionViewModel,
dont pass viewModel in here, interact with the viewmodel only from one function.

2024-06-02 06:21 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/savings_account_transaction/SavingAccountsTransactionScreen.kt
> +                                icon = Icons.Filled.CompareArrows)
dont make another function, adapt MifosErrorComponent generic so it can accomodate to your requirements as well.

2024-06-02 06:21 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/savings_account_transaction/SavingAccountsTransactionScreen.kt
> +                else -> Unit
no need of else. make a new SavingsAccountTransactionUiState in viewmodel specific to only this screen.

2024-06-02 06:21 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/savings_account_transaction/SavingAccountsTransactionScreen.kt
> +fun SavingsAccountTransactionListItem(transaction: Transactions?) {
dont pass nullable type

2024-06-02 06:21 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/savings_account_transaction/SavingAccountsTransactionScreen.kt
> +    viewModel: SavingAccountsTransactionViewModel,
dont pass viewmodel in here

2024-06-18 13:59 UTC, therajanmaurya approved these changes

2024-06-18 13:59 UTC, merged