refactor: Migrate Settings from XML to compose
openMF/self-service-app pull request #2601
Opened 2024-06-03 21:56 UTC by itsPronay

Fixes #2570 

xml | compose 
------|--------------
![image](https://github.com/openMF/mifos-mobile/assets/78101731/74a55a7c-43b9-4b53-85e1-5e1a5bc30afa) | ![image](https://github.com/openMF/mifos-mobile/assets/78101731/96151ce4-e8b5-42e1-98c5-e5a0c33df0bd)

[Screencast_06_04_2024_03:29:22_AM.webm](https://github.com/openMF/mifos-mobile/assets/78101731/806088ae-a34d-4d8c-9f76-fca7fa90f3dc)

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2024-06-04 01:51 UTC, therajanmaurya commented
<img width="312" alt="image" src="https://github.com/openMF/mifos-mobile/assets/5724482/ba54b9c3-4b34-47ff-a434-5d4acff4e350">
Give 16dp end padding to update endpoint description

2024-06-11 18:18 UTC, AvneetSingh2001 requested changes

2024-06-11 18:18 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/settings/SettingsFragment.kt
> +            }.show()
Migrate Alert dialogs as well in compose

2024-06-11 18:18 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/settings/SettingsFragment.kt
> +        MaterialAlertDialogBuilder(requireContext()).setTitle(getString(R.string.change_app_theme))
migrate dialog to compose

2024-06-14 13:22 UTC, itsPronay commented on app/src/main/java/org/mifos/mobile/ui/settings/SettingsFragment.kt
> +            }.show()
done

2024-06-17 16:30 UTC, AvneetSingh2001 requested changes

2024-06-17 16:30 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/settings/SettingsFragment.kt
> +    }
do this in compose screen.

2024-06-17 16:30 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/settings/SettingsFragment.kt
> +    }
update shared prefs from compose screen only

2024-06-17 16:30 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/settings/SettingsFragment.kt
> +    }
in compose screen

2024-06-17 16:30 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/settings/SettingsFragment.kt
> +    }
in compose screen

2024-06-17 16:30 UTC, AvneetSingh2001 commented on app/src/main/java/org/mifos/mobile/ui/settings/SettingsScreen.kt
> +    Scaffold(
use MF SCaffold

2024-06-18 20:43 UTC, closed without merging