third party transfer migration
openMF/self-service-app pull request #2603
Opened 2024-06-11 15:58 UTC by AvneetSingh2001

Fixes #Issue_Number

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2024-06-13 18:39 UTC, Aditya-gupta99 approved these changes
LGTM

2024-06-14 15:51 UTC, PratyushSingh07 requested changes

2024-06-14 15:51 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/third_party_transfer/ThirdPartyTransferScreen.kt
> +    val uiState = viewModel.thirdPartyTransferUiState.collectAsStateWithLifecycle()
use by delegate & then directly pass uiState instead of uiState.value

2024-06-14 15:51 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/third_party_transfer/ThirdPartyTransferScreen.kt
> +        uiData = uiData.value,
same as above

2024-06-14 15:51 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/third_party_transfer/ThirdPartyTransferScreen.kt
> +fun ThirdPartyTransferScreenPreview() {
preview for other ui states ?

2024-06-14 15:51 UTC, PratyushSingh07 commented on app/src/main/java/org/mifos/mobile/ui/third_party_transfer/ThirdPartyTransferContent.kt
> +                Button(
better to create a component for buttons

2024-06-14 16:32 UTC, merged