Update Status Bar to Match Theme Colors Dynamically
openMF/self-service-app pull request #2711
Opened 2024-09-20 14:03 UTC by Saifuddin53

Fixes #2710

Please Add Screenshots If there are any UI changes.

Light theme: 

| Before | After |
|---|---|
| ![WhatsApp Image 2024-09-20 at 07 18 27_ea2a1732](https://github.com/user-attachments/assets/73fd11f3-619c-4f91-9d16-b58d5f26fff9) | ![WhatsApp Image 2024-09-20 at 19 23 42_1972390b](https://github.com/user-attachments/assets/3c1e1326-6dcf-404c-b693-a1a4ad98731a)

Dark theme: 

| Before | After |
|---|---|
| ![WhatsApp Image 2024-09-20 at 07 18 28_e1b27c20](https://github.com/user-attachments/assets/19f03e71-607b-4d34-acb9-331383f17dd6) | ![WhatsApp Image 2024-09-20 at 19 23 42_fb409385](https://github.com/user-attachments/assets/320edbc8-9a5b-4af4-ba23-8a81406fc501)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2024-09-20 20:01 UTC, niyajali requested changes

2024-09-20 20:01 UTC, niyajali commented on core/designsystem/src/main/kotlin/org/mifos/mobile/core/designsystem/theme/Theme.kt
> +    }
Use `enableEdgeToEdge()` API, and set status bar color to **Transperant** in both light and dark theme.

2024-09-26 16:25 UTC, niyajali requested changes

2024-09-26 16:25 UTC, niyajali commented on core/designsystem/src/main/kotlin/org/mifos/mobile/core/designsystem/theme/Theme.kt
> +        SideEffect {
we no need to configuring it manually this should be provided by EnableEdgeToEdge Api, you could configure theme for night & dark mode like below

update `splash.xml`
```
<resources xmlns:tools="http://schemas.android.com/tools">

    <!-- Allows us to override night specific attributes in the
     values-night folder. -->
    <style name="NightAdjusted.Theme" parent="android:Theme.Material.Light.NoActionBar">
        <item name="android:statusBarColor">@color/status_bar</item>
    </style>

    <!-- The final theme we use -->
    <style name="Theme.Nia" parent="NightAdjusted.Theme" />

    <style name="NightAdjusted.Theme.Splash" parent="Theme.SplashScreen">
        <item name="android:windowLightNavigationBar" tools:targetApi="27">true</item>
    </style>

    <style name="Theme.Mifos.Splash" parent="NightAdjusted.Theme.Splash">
        <item name="windowSplashScreenAnimatedIcon">@drawable/splash_icon</item>
        <item name="postSplashScreenTheme">@style/Theme.Nia</item>
    </style>

</resources>
```

create values-night folder and create `theme.xml, colors.xml` file
values-night/theme.xml would be look like this
```
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools">

    <style name="NightAdjusted.Theme" parent="android:Theme.Material.NoActionBar">
        <item name="android:statusBarColor">@color/status_bar</item>
    </style>

    <style name="NightAdjusted.Theme.Splash" parent="Theme.SplashScreen">
        <item name="android:windowLightNavigationBar" tools:targetApi="27">false</item>
    </style>

</resources>
```
`color.xml`
```
<color name="status_bar">#FFFEFBFF</color> // light/color.xml
<color name="status_bar">#FF1B1B1F</color> // dark/color.xml
```
`HomeActivity.kt`

```
       setContent {
            val darkTheme = isSystemInDarkTheme()

            // Update the dark content of the system bars to match the theme
            DisposableEffect(darkTheme) {
                enableEdgeToEdge(
                    statusBarStyle = SystemBarStyle.auto(
                        Color.TRANSPARENT,
                        Color.TRANSPARENT,
                    ) { darkTheme },
                    navigationBarStyle = SystemBarStyle.auto(
                        lightScrim,
                        darkScrim,
                    ) { darkTheme },
                )

                onDispose {}
            }
     }
```

you may need to configure TopAppBar colors as well, update DarkThemeColors
`surface = BackgroundDark` 

you may need to do some small tweaks to match these StatusBar, NavigationBar and Surface colors to same.

2024-10-10 04:39 UTC, Saifuddin53 commented on core/designsystem/src/main/kotlin/org/mifos/mobile/core/designsystem/theme/Theme.kt
> +        SideEffect {
@niyajali I have updated the code and screenshots can you please recheck it

2024-10-10 09:15 UTC, therajanmaurya commented
is it ready for final review @niyajali

2024-10-10 13:56 UTC, niyajali commented
@therajanmaurya looks good to me..and it's ready for the final review

2024-10-15 12:18 UTC, Saifuddin53 commented
@therajanmaurya can we merge this PR?

2024-12-20 11:37 UTC, closed without merging