fix: notifications rendering issue
openMF/self-service-app pull request #2720
Opened 2024-12-05 16:50 UTC by Nagarjuna0033

Fixes [#MM-87](https://mifosforge.jira.com/browse/MM-87)

| Before | Current |
|-------------|------------|
| <img src="https://github.com/user-attachments/assets/59583890-87cc-4105-b2a7-8b5a669803a9" width="300"/> | <img src="https://github.com/user-attachments/assets/b923b28c-2345-4261-b2fc-6dea86c981d2" width="300"/> | 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2024-12-05 19:30 UTC, therajanmaurya requested changes

2024-12-05 19:30 UTC, therajanmaurya commented on androidApp/src/main/kotlin/org/mifos/mobile/HomeActivity.kt
> +        FlowManager.init(this)
we should initialize it Application class. Please try and check

2024-12-05 19:30 UTC, therajanmaurya commented on core/datastore/src/main/java/org/mifos/mobile/core/datastore/DatabaseHelper.kt
> +        Log.d("Notifications@@@", notifications.toString())
Log as Gson().json(notifications)

2024-12-06 09:07 UTC, Nagarjuna0033 commented on core/datastore/src/main/java/org/mifos/mobile/core/datastore/DatabaseHelper.kt
> +        Log.d("Notifications@@@", notifications.toString())
@therajanmaurya Sir, I have implemented the changes. Could you please take a look?

2024-12-09 19:03 UTC, merged