refractor: Transfer Screen
openMF/self-service-app pull request #329
Opened 2017-07-01 16:19 UTC by dilpreet96

<img src="https://user-images.githubusercontent.com/12071739/27763735-f76a38ea-5ea6-11e7-8ac5-8bb5ff773392.gif"/>

@therajanmaurya  @puneetkohli521 please review.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2017-07-04 19:17 UTC, therajanmaurya commented
@dilpreet96 Looks good.

2017-07-04 19:17 UTC, dilpreet96 commented
Thanks @therajanmaurya

2017-07-04 19:25 UTC, therajanmaurya requested changes

2017-07-04 19:25 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/presenters/TransferProcessPresenter.java
> +public class TransferProcessPresenter extends BasePresenter<TransferProcessView> {
@dilpreet96 there is no attach and detach implemented, It can be Observer leakage then It will be hard to find.

2017-07-04 19:25 UTC, therajanmaurya commented on app/src/main/res/layout/fragment_transfer_process.xml
> +<android.support.v4.widget.NestedScrollView
👍 Great you are using NestedScrollView

2017-07-04 19:51 UTC, dilpreet96 commented on app/src/main/java/org/mifos/selfserviceapp/presenters/TransferProcessPresenter.java
> +public class TransferProcessPresenter extends BasePresenter<TransferProcessView> {
@therajanmaurya Changes made

2017-07-06 06:45 UTC, therajanmaurya commented
@dilpreet96 Please fix the conflicts

2017-07-06 07:25 UTC, dilpreet96 commented
@therajanmaurya conflicts fixed

2017-07-06 07:31 UTC, therajanmaurya approved these changes

2017-07-06 07:31 UTC, merged