feat:Filter in accounts
openMF/self-service-app pull request #331
Opened 2017-07-03 16:07 UTC by dilpreet96

Demo: 

<img src="https://user-images.githubusercontent.com/12071739/27800592-b8537148-6037-11e7-8a54-5d411b13a656.gif"/>

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2017-07-03 16:50 UTC, dilpreet96 commented
@therajanmaurya please review it

2017-07-04 19:36 UTC, therajanmaurya requested changes

2017-07-04 19:36 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/ui/adapters/CheckBoxAdapter.java
> +            itemView.setOnClickListener(new View.OnClickListener() {
@dilpreet96 we are using ButterKnife Please use annotation

2017-07-04 19:36 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/ui/fragments/ClientAccountsFragment.java
> +    private void initSearchSavings(Menu menu) {
@dilpreet96 you can make the single generic type of method, By just passing 2 -3 parameter and if statements and can use anywhere. Please do

2017-07-04 19:36 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/ui/fragments/ClientAccountsFragment.java
> +    private void showSavingsFilterDialog() {
Same as above

2017-07-04 19:37 UTC, dilpreet96 commented on app/src/main/java/org/mifos/selfserviceapp/ui/fragments/ClientAccountsFragment.java
> +    private void initSearchSavings(Menu menu) {
On it :+1:

2017-07-04 19:40 UTC, dilpreet96 commented on app/src/main/java/org/mifos/selfserviceapp/ui/fragments/ClientAccountsFragment.java
> +    private void showSavingsFilterDialog() {
On it :+1:

2017-07-04 20:12 UTC, dilpreet96 commented
@therajanmaurya changes made

2017-07-06 06:44 UTC, therajanmaurya approved these changes

2017-07-06 06:44 UTC, merged