feat: Add beneficiary using Qr Code
openMF/self-service-app pull request #332
Opened 2017-07-06 18:21 UTC by dilpreet96

<img src="https://user-images.githubusercontent.com/12071739/27926314-9c466026-62a5-11e7-9e1b-e7afd64e5e4f.gif" />

<img src="https://user-images.githubusercontent.com/12071739/27926348-becae11c-62a5-11e7-807d-db8b8c740552.png"  width=250 height = 450/> <img src="https://user-images.githubusercontent.com/12071739/27926347-bec98628-62a5-11e7-9e7d-4aaf10df40fa.png"  width=250 height = 450/>

Loan Creation:
<img src="https://user-images.githubusercontent.com/12071739/27926375-db0ff38a-62a5-11e7-982d-45d174b209e3.png"  width=250 height = 450/>

Please make sure these boxes are checked before submitting your pull request - thanks!
- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2017-07-06 18:35 UTC, dilpreet96 commented
@therajanmaurya please review

2017-07-08 14:01 UTC, dilpreet96 commented
@therajanmaurya fixed navigation drawer according to the discussion

2017-07-10 11:28 UTC, therajanmaurya commented
No, you don't need to change. I will review today. It looks good to me.

2017-07-12 12:20 UTC, therajanmaurya requested changes

2017-07-12 12:20 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/ui/activities/HomeActivity.java
> +            Log.d(HomeActivity.class.getName(), "permission granted");
What if use will deny the permission?

2017-07-12 12:20 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/ui/fragments/HomeFragment.java
> +                .setTitle("Choose Transfer Type")
don't use hardcoded string, add in strings.xml

2017-07-12 15:22 UTC, dilpreet96 commented on app/src/main/java/org/mifos/selfserviceapp/ui/activities/HomeActivity.java
> +            Log.d(HomeActivity.class.getName(), "permission granted");
@therajanmaurya changes made

2017-07-14 07:02 UTC, therajanmaurya requested changes

2017-07-14 07:02 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/ui/activities/HomeActivity.java
> +                                           @NonNull int[] grantResults) {
@dilpreet96  Please look this https://github.com/openMF/android-client/blob/master/mifosng-android/src/main/java/com/mifos/utils/CheckSelfPermissionAndRequest.java

2017-07-14 10:03 UTC, dilpreet96 commented
@therajanmaurya changes made

2017-07-21 17:39 UTC, therajanmaurya approved these changes

2017-07-21 17:39 UTC, merged