feat: User details
openMF/self-service-app pull request #338
Opened 2017-07-10 18:21 UTC by dilpreet96

![ss](https://user-images.githubusercontent.com/12071739/28033090-7f61e264-65ca-11e7-841c-3d904d5b378e.gif)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2017-07-12 12:23 UTC, therajanmaurya requested changes

2017-07-12 12:23 UTC, therajanmaurya commented on app/src/main/java/org/mifos/selfserviceapp/ui/fragments/HomeFragment.java
> +                        setOnClickListener(new View.OnClickListener() {
Use Butterknife @onClick annotation instead `setOnClickListener(..)`

2017-07-12 15:53 UTC, dilpreet96 commented on app/src/main/java/org/mifos/selfserviceapp/ui/fragments/HomeFragment.java
> +                        setOnClickListener(new View.OnClickListener() {
@therajanmaurya as toolbar custom view is added in onResume and removed at onPause state https://github.com/dilpreet96/self-service-app/blob/abb8736564ef83d009489ce19c05234953c7da88/app/src/main/java/org/mifos/selfserviceapp/ui/fragments/HomeFragment.java#L207
so, butterknife is not be able to find the image as it is added at runtime due to which I used the manual method

2017-07-14 07:02 UTC, therajanmaurya approved these changes

2017-07-14 07:03 UTC, merged