tests: BeneficiaryApplication and LoanApplication test
openMF/self-service-app pull request #340
Opened 2017-07-12 12:01 UTC by dilpreet96

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2017-07-12 12:30 UTC, therajanmaurya requested changes

2017-07-12 12:30 UTC, therajanmaurya commented on app/src/test/java/org/mifos/selfserviceapp/BeneficiaryApplicationPresenterTest.java
> +        when(context.getString(R.string.error_fetching_beneficiary_template)).
@dilpreet96 use strings.xml values instead of hardcoded string.

2017-07-12 16:01 UTC, dilpreet96 commented on app/src/test/java/org/mifos/selfserviceapp/BeneficiaryApplicationPresenterTest.java
> +        when(context.getString(R.string.error_fetching_beneficiary_template)).
@therajanmaurya as these are junit tests cases and I am trying to mock `getString()` method so how can we use strings.xml values in `thenReturn()` function?

2017-07-14 07:04 UTC, therajanmaurya commented on app/src/test/java/org/mifos/selfserviceapp/BeneficiaryApplicationPresenterTest.java
> +        when(context.getString(R.string.error_fetching_beneficiary_template)).
already mocked the Context, I don't think you need to

2017-07-14 07:53 UTC, dilpreet96 commented on app/src/test/java/org/mifos/selfserviceapp/BeneficiaryApplicationPresenterTest.java
> +        when(context.getString(R.string.error_fetching_beneficiary_template)).
@therajanmaurya changes made. Thank you for pointing that out.

2017-07-14 16:06 UTC, therajanmaurya approved these changes

2017-07-14 16:06 UTC, merged