feat: translated mobile banking app to hindi
openMF/self-service-app pull request #408
Opened 2017-09-15 17:14 UTC by amanjeetsingh150

Fixes #{407}

Please Add Screenshots If any UI changes.

<img src="https://user-images.githubusercontent.com/12881364/30494740-fab00c40-9a66-11e7-9de3-a1dbea3a1bb2.png" height=500/> <br> <img src="https://user-images.githubusercontent.com/12881364/30494751-00b996e2-9a67-11e7-9cae-695786f2ea81.png" height=500/>

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2017-09-15 23:10 UTC, amanjeetsingh150 commented
@dilpreet96 @therajanmaurya please review.

2017-09-20 10:01 UTC, therajanmaurya commented
@amanjeetsingh150 Before the review, Please revert Gradle version and Gradle tools version change. This issue does not contain this type of change. After changing let me know.

2017-09-20 20:25 UTC, amanjeetsingh150 commented
@therajanmaurya on it will submit the updated PR soon 👍

2017-09-21 14:54 UTC, amanjeetsingh150 commented
@therajanmaurya @dilpreet96 reverted the gradle tool and gradle versions.
Please review!

2017-10-02 16:22 UTC, therajanmaurya requested changes

2017-10-02 16:22 UTC, therajanmaurya commented on app/src/main/res/values-hi/strings.xml
> +    <string name="app_name">सेल्फ सर्विस ऐप</string>
@amanjeetsingh150 Please don't translate app name

2017-10-02 16:23 UTC, therajanmaurya commented
@amanjeetsingh150 Please make the above change first,  I want this PR merge first.

2017-10-02 17:49 UTC, amanjeetsingh150 commented
@therajanmaurya changed the app name back to English. Please review.

2017-10-02 18:44 UTC, therajanmaurya approved these changes

2017-10-02 19:45 UTC, merged