fix: Changed InputType of some editText in new registration screen
openMF/self-service-app pull request #477
Opened 2017-10-27 20:37 UTC by Rish02Sharma

Fixes #476 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2017-10-30 20:02 UTC, therajanmaurya requested changes

2017-10-30 20:02 UTC, therajanmaurya commented on app/src/main/res/layout/fragment_registration.xml
> +            android:inputType="number"/>
@Rish02Sharma account number should be text type. It can consist a-z and 0-9 etc.

2017-10-30 20:02 UTC, therajanmaurya commented on app/src/main/res/layout/fragment_registration.xml
> +</LinearLayout>
Add a single black line at the last.

2017-10-30 20:02 UTC, therajanmaurya commented
@Rish02Sharma Please make request changes and squash your commits.

2017-11-02 20:35 UTC, Rish02Sharma commented on app/src/main/res/layout/fragment_registration.xml
> +</LinearLayout>
Done :+1:

2017-11-02 20:36 UTC, Rish02Sharma commented
Done :+1: ....Please review.

2017-11-03 11:33 UTC, therajanmaurya approved these changes

2017-11-03 11:33 UTC, merged