refractor: Rename app and package name
openMF/self-service-app pull request #487
Opened 2017-11-18 07:22 UTC by dilpreet96

Package name changed to : `org.mifos.mobilebanking` 
App name changed to: `Mifos Mobile`

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2017-11-18 17:54 UTC, therajanmaurya requested changes

2017-11-18 17:54 UTC, therajanmaurya commented on app/src/main/res/values-hi/strings.xml
> -    <string name="app_name">Self Service App</string>
@dilpreet96 Don't remove this string.

2017-11-18 17:54 UTC, therajanmaurya commented
@dilpreet96 Make the above changes.

2017-11-18 20:33 UTC, dilpreet96 commented
@therajanmaurya done

2017-11-19 09:12 UTC, therajanmaurya approved these changes

2017-11-19 09:12 UTC, merged