test: Unit Test for ClientChargePresenter
openMF/self-service-app pull request #505
Opened 2017-12-11 16:58 UTC by luckyman20

Fixes #493

@dilpreet96 Please review it!!

2017-12-11 18:18 UTC, dilpreet2028 requested changes
@luckyman20 , make the changes and your travis build is failing please fix it , you can see here the reason for the fail: https://travis-ci.org/openMF/mifos-mobile/builds/314891340#L3087

2017-12-11 18:18 UTC, dilpreet96 commented on app/src/test/java/org/mifos/mobilebanking/ClientChargePresenterTest.java
> +        when(dataManager.getLoanCharges(1)).thenReturn(Observable.just(charge.getPageItems()));
You have to use loan charges json, the one which I gave in the mail

2017-12-11 18:18 UTC, dilpreet96 commented on app/src/test/java/org/mifos/mobilebanking/ClientChargePresenterTest.java
> +        when(dataManager.getSavingsCharges(1)).thenReturn(Observable.just(charge.getPageItems()));
Same goes here, use savings charges from the mail

2017-12-12 02:54 UTC, luckyman20 commented
@dilpreet96 Updated the PR

2017-12-12 06:39 UTC, dilpreet2028 approved these changes

2017-12-12 06:39 UTC, merged