fix: Issue #446 - End Date datepicker should be initialised to the date of start date
openMF/self-service-app pull request #536
Opened 2018-01-17 15:00 UTC by luckyman20

Fixes #446

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2018-02-09 11:28 UTC, dilpreet2028 requested changes
Good work @luckyman20 , make the changes and also add a gif.

2018-02-09 11:28 UTC, dilpreet96 commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsTransactionFragment.java
> +    public long startDateFromPicker , endDateFromPicker;
Make them private @luckyman20

2018-02-09 11:28 UTC, dilpreet96 commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsTransactionFragment.java
> +    public DatePick datePick;
Make this private

2018-02-11 10:01 UTC, luckyman20 commented
![ezgif com-optimize](https://user-images.githubusercontent.com/20682192/36072140-83fc6694-0f40-11e8-8e1c-fa5b3f254fed.gif)

@dilpreet96 Done !! :-)

2018-02-13 07:12 UTC, dilpreet2028 requested changes
Good work @luckyman20 , but this DatePicker is also being used in other activity i.e. LoanApplicationFragment where we don't have to select a min and a max date, so for that you can initialise isStart = true in the newInstance method as a default.

2018-02-13 07:12 UTC, dilpreet96 commented on app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java
> +    public String startDateString;
Make it private.

2018-02-13 07:12 UTC, dilpreet96 commented on app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java
> +    public long startDate;
Make it private.

2018-02-13 07:12 UTC, dilpreet96 commented on app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java
> +    boolean isStart;
Make it private.

2018-02-13 07:12 UTC, dilpreet96 commented on app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java
> +    public boolean isStartDate(boolean isStart) {
As you are using this function to just update the isStart Value so you can change the return type to void and Remove the return statement.

2018-02-13 08:10 UTC, luckyman20 commented
@dilpreet96 Made the Changes :-)

2018-02-14 11:16 UTC, dilpreet96 commented
Good work @luckyman20

2018-02-14 11:16 UTC, dilpreet2028 approved these changes

2018-02-14 11:17 UTC, merged