fix : Minimum required balance label hidden on null data
openMF/self-service-app pull request #541
Opened 2018-01-28 18:24 UTC by geekanamika

Fixes #465
![screenshot_2018-01-28-23-37-39-567_org mifos mobilebanking](https://user-images.githubusercontent.com/16922933/35485371-dde235e2-0484-11e8-8903-f02adfeee4f2.png)
![screenshot_2018-01-28-23-37-51-107_org mifos mobilebanking](https://user-images.githubusercontent.com/16922933/35485372-de50b7a6-0484-11e8-960b-4bf665eccac4.png)

2018-02-02 14:16 UTC, dilpreet2028 requested changes

2018-02-02 14:16 UTC, dilpreet96 commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsDetailFragment.java
> +    TextView minRequiredBalanceLabel;
@geekanamika , can you rename it as `tvMinRequiredBalanceLabel`

2018-02-07 18:21 UTC, geekanamika commented
@dilpreet96 I have updated it, Can you please review now ? Thank you

2018-02-09 11:29 UTC, dilpreet2028 approved these changes

2018-02-09 11:29 UTC, merged