Issue#553: Fixed Ui error in User Profile
openMF/self-service-app pull request #605
Opened 2018-02-13 15:11 UTC by ivary43

Fixes #553

Please Add Screenshots If any UI changes.
![20180213_203227](https://user-images.githubusercontent.com/24601454/36156646-b6153476-10fd-11e8-9a69-296a5ac5b0c9.gif)

Please make sure these boxes are checked before submitting your pull request - thanks!

- \[x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- \[x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- \[x] If you have multiple commits please combine them into one commit by squashing them.

2018-02-13 15:12 UTC, ivary43 commented
@dilpreet96 , @therajanmaurya  please review.

2018-02-20 18:29 UTC, roychowdhuryrohit-dev commented
Please merge this issue. @dilpreet96  @therajanmaurya

2018-02-28 14:41 UTC, dilpreet2028 requested changes

2018-02-28 14:41 UTC, dilpreet96 commented on app/src/main/res/layout/fragment_user_profile.xml
> +            android:visibility="visible">
@ivary43 I don't thing we need to declare visibility( as visible) as it is the default so can you remove this?

2018-02-28 22:17 UTC, ivary43 commented
@dilpreet96  done. Please review :)

2018-03-02 11:58 UTC, dilpreet2028 approved these changes

2018-03-02 11:59 UTC, dilpreet96 commented
@ivary43 can you change follow your commit message to the guidelines : https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide#the-type

2018-03-02 12:11 UTC, ivary43 commented
@dilpreet96 done.

2018-03-11 12:07 UTC, dilpreet96 commented
@ivary43 you have changed the title of this PR not the commit message

2018-03-11 13:03 UTC, ivary43 commented
@dilpreet96 I have changed the commit message please review.

2018-03-12 20:28 UTC, merged