fix #650: Softkeyboard blocks the UI
openMF/self-service-app pull request #695
Opened 2018-03-01 12:53 UTC by miPlodder

Fixes #650 

![pr_softkeyboard](https://user-images.githubusercontent.com/22195621/36845613-796de2f2-1d7d-11e8-8b48-040e4fafcff4.gif)

![pr_softkeyboard_2](https://user-images.githubusercontent.com/22195621/36845619-7e99b99a-1d7d-11e8-84c0-a300d9606d12.gif)

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2018-03-01 12:53 UTC, miPlodder commented
@dilpreet96 @satyan @droidchef Please review this PR.

2018-03-11 05:52 UTC, therajanmaurya requested changes

2018-03-11 05:52 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/ui/activities/HomeActivity.java
> +                imm.hideSoftInputFromWindow(drawerView.getWindowToken(), 0);
Please make method in Base Activity and use it here 
```
public void hideKeyboard(View view) {
        InputMethodManager inputManager = (InputMethodManager) this
                 .getSystemService(Context.INPUT_METHOD_SERVICE);
        inputManager.hideSoftInputFromWindow(view.getWindowToken(), InputMethodManager
                 .RESULT_UNCHANGED_SHOWN);
    }
```

2018-03-13 09:35 UTC, miPlodder commented
@therajanmaurya I have made the requested changes. Please review this PR.

2018-03-15 17:49 UTC, therajanmaurya requested changes

2018-03-15 17:49 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/ui/activities/HomeActivity.java
> +
Remove this blank link.

2018-03-15 17:49 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/ui/activities/HomeActivity.java
> +
Remove this blank link.

2018-03-15 17:49 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/ui/activities/HomeActivity.java
> +
Remove this blank link.

2018-03-15 17:49 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/ui/activities/HomeActivity.java
> +
Remove this blank link.

2018-03-15 17:49 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/ui/activities/HomeActivity.java
> +
Remove this blank link.

2018-03-15 18:00 UTC, miPlodder commented
@therajanmaurya Please review again. I have made the requested changes.

2018-03-17 19:02 UTC, therajanmaurya approved these changes

2018-03-17 19:02 UTC, merged