RTL Support Addition
openMF/self-service-app pull request #71
Opened 2016-12-10 02:03 UTC by superav

Layout files have been edited and changed so that they allow support for lanugauge scripts that read from right to left and those that read left to right.

2016-12-10 06:32 UTC, tarun0 requested changes
Missed [this](https://github.com/superav/self-service-app/blob/dbfc32e81774e89e5065f5b59400478dd64cfdb6/app/src/main/res/layout/activity_saving_account_details.xml#L35) maybe?

Please make these small changes and submit the task again.

2016-12-10 06:32 UTC, tarun0 commented on app/src/main/res/layout/activity_loan_account_details.xml
>          android:paddingLeft="@dimen/row_padding_left"
This line is redundant as the minApiVersion is 17. `android:paddingStart="@dimen/row_padding_left"` in itself is sufficient.

2016-12-11 01:05 UTC, tarun0 commented
@superav Please squash the 3 commits into a single commit. Then @therajanmaurya will review it finally before merging.

2016-12-11 03:52 UTC, mdew192837 reviewed
@tarun0 I have a few questions. Just trying to learn. :) Should we leave paddingLeft for backwards compatibility? You mentioned miniApiVersion 17. Does that mean paddingLeft is not needed? Also, should we add android:supportsRtl="true" in the AndroidManifest.xml file?

2016-12-11 05:23 UTC, tarun0 commented
@mdew192837 Yes, to support RTL, one must enable it in the manifest file by using `android:supportsRtl="true"`. Since the app's minSdkVersion is 17, it means that this app can't be installed in the Android versions below Jellybean (any API < 17). The attributes such as paddingLeft are used with API<17 (or if RTL is disabled in manifest). 
Since RTL is already enabled (this is why you can't find the change in the commits) and the minSdkVersion for the app is 17, we don't need marginLeft because marginLeft and marginStart will mean the same.

Hope that clarifies your query.

2016-12-11 19:02 UTC, closed without merging