Removed the onBackPressed Bug in TransferProcessFragment
openMF/self-service-app pull request #724
Opened 2018-03-13 09:29 UTC by sridharjajoo

Fixes #665 
![device-2018-03-13-144249](https://user-images.githubusercontent.com/20684618/37332889-ecb48ff0-26cd-11e8-8074-5e4fa1cf89b1.gif)

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2018-03-13 09:49 UTC, miPlodder commented
@sridharjajoo Please release Checkstyle errors from link below and update the PR.

https://travis-ci.org/openMF/mifos-mobile/builds/352745365#L2888

2018-03-13 11:28 UTC, sridharjajoo commented
@therajanmaurya @dilpreet96 Kindly review!

2018-03-17 18:54 UTC, therajanmaurya requested changes

2018-03-17 18:54 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/TransferProcessFragment.java
> +
Remove this blank line.

2018-03-17 18:54 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/TransferProcessFragment.java
> +
Remove this blank line.

2018-03-17 18:56 UTC, therajanmaurya commented
@sridharjajoo Please follow commit guideline. you can find guideline doc in wiki.

2018-03-17 19:09 UTC, sridharjajoo commented
@therajanmaurya Thanks! Will take care of that in future.

2018-03-17 19:22 UTC, sridharjajoo commented
@therajanmaurya Done the changes!

2018-03-17 20:06 UTC, therajanmaurya commented
@sridharjajoo you commit message supposed to be this 
`Fix: Removed the onBackPressed Bug in TransferProcessFragment`

2018-03-17 20:09 UTC, sridharjajoo commented
@therajanmaurya Done the required changes!

2018-03-22 11:49 UTC, sridharjajoo commented
@therajanmaurya Kindly review!

2018-04-12 18:23 UTC, merged