fix: added scroll to ensure visibility of withdraw loan button for lo…
openMF/self-service-app pull request #725
Opened 2018-03-13 11:11 UTC by mohak1712

Fixes #696 

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12782512/37337590-cb32560c-26da-11e8-8a16-3747e7e0f1d8.gif)

2018-03-13 11:12 UTC, mohak1712 commented
@therajanmaurya  @dilpreet96 please review

2018-03-17 18:51 UTC, therajanmaurya requested changes

2018-03-17 18:51 UTC, therajanmaurya commented on app/src/main/res/layout/fragment_loan_withdraw.xml
> +<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
Please use NestedScrollView.

2018-03-18 05:42 UTC, mohak1712 commented
@therajanmaurya I have made the changes 
Please review

2018-03-18 14:28 UTC, merged