Fix #703 : Forms not loaded, when no Internet Connection
openMF/self-service-app pull request #730
Opened 2018-03-13 18:35 UTC by miPlodder

Fixes #703

![pr_703](https://user-images.githubusercontent.com/22195621/37359780-7efd2ffc-2714-11e8-9ad6-5bf41e6da289.gif)

![pr_703_2](https://user-images.githubusercontent.com/22195621/37359788-82ef9a00-2714-11e8-8088-0ac872ba49a8.gif)

Similarly, for Third Party Transfer.

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2018-03-13 18:36 UTC, miPlodder commented
@therajanmaurya @dilpreet96 @droidchef @satyan Please review this PR.

2018-04-12 18:38 UTC, therajanmaurya commented
@miPlodder Please use Sweet Error UI.

2018-04-27 15:17 UTC, miPlodder commented
@therajanmaurya Please review the PR. I have made the requested changes and updated the GIF's.

2018-06-04 10:53 UTC, therajanmaurya requested changes

2018-06-04 10:53 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryApplicationFragment.java
> +    @BindView(R.id.view_flipper)
id name is not, make it nsvBeneficiary

2018-06-04 10:53 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryApplicationFragment.java
> +    View layout_error;
use camel case naming convention, it should be layoutError

2018-06-04 10:54 UTC, therajanmaurya commented
@miPlodder Fix the conflict and make requested changes.

2018-06-04 12:30 UTC, miPlodder commented
@therajanmaurya Please review this PR again.

2018-06-04 12:35 UTC, miPlodder commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryListFragment.java
> +        if (beneficiaryList != null) {
@therajanmaurya Without null pointer check, the app was crashing. (Maybe because of migration from Fragment to activity)

2018-06-04 17:18 UTC, therajanmaurya approved these changes

2018-06-05 03:18 UTC, merged