Fix #736 : User Profile UI Issue [Offline Mode]
openMF/self-service-app pull request #768
Opened 2018-03-19 19:14 UTC by miPlodder

Fixes #736 

![pr_736](https://user-images.githubusercontent.com/22195621/37617028-d7223480-2bd7-11e8-8859-b68018239dd3.gif)

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2018-03-19 19:15 UTC, miPlodder commented
@therajanmaurya @dilpreet96 @droidchef @satyan Please review this PR.

2018-04-12 18:27 UTC, therajanmaurya commented
@miPlodder Please use sweet error library.

2018-04-14 10:31 UTC, miPlodder commented
@therajanmaurya Please review the PR again, I have made the requested changes.

2018-04-14 10:53 UTC, miPlodder commented
@therajanmaurya Please review this PR again, I have made the requested changes.

2018-05-06 16:16 UTC, therajanmaurya requested changes

2018-05-06 16:16 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/UserProfileFragment.java
> +        sweetUIErrorHandler.showSweetCustomErrorUI(getString(R.string.error_message_server),
Error message should be `Failed to fetch user profile`

2018-05-06 16:36 UTC, miPlodder commented
@therajanmaurya I have made the requested changes. Please review again.

2018-06-01 06:38 UTC, therajanmaurya approved these changes

2018-06-01 06:38 UTC, merged