Feat #833: Added Support for Applying Savings Account
openMF/self-service-app pull request #867
Opened 2018-07-01 15:17 UTC by miPlodder

Fixes #833 

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2018-07-01 15:29 UTC, miPlodder commented
@therajanmaurya Please review this PR.

2019-01-29 16:46 UTC, miPlodder commented
@therajanmaurya Withdrawal API are using Fake Responses and other are using the newly deployed API's and UI changed.

2019-02-24 05:41 UTC, therajanmaurya requested changes

2019-02-24 05:41 UTC, therajanmaurya commented on app/build.gradle
> +            java.srcDir commonTestDir
Why this,  we already added the commonTestDir above.
See: https://github.com/openMF/mifos-mobile/pull/867/files#diff-39e7d8c00954e920b98e7636f0ac30b2R38

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/models/accounts/savings/SavingsAccountWithdrawPayload.java
> +public class SavingsAccountWithdrawPayload {
Convert this payload into kotlin.

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/models/templates/savings/ChargeOptions.kt
> +
Remove this blank line.

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/presenters/SavingsAccountApplicationPresenter.java
> +        getMvpView().showProgress();
Check view `checkViewAttached();` is attached or not.

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/presenters/SavingsAccountApplicationPresenter.java
> +    DataManager dataManager;
Make this private

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/presenters/SavingsAccountApplicationPresenter.java
> +    CompositeDisposable compositeDisposable;
make this private

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/models/templates/savings/SavingsAccountTemplate.kt
> +
Remove this blank line.

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/models/templates/savings/ProductOptions.kt
> +
Remove this blank line.

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/models/templates/savings/ProductOptions.kt
> +
Remove this blank line.

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/models/templates/savings/ChargePaymentMode.kt
> +
Remove this blank line.

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/models/templates/savings/ChargeOptions.kt
> +
Remove this blank line.

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/presenters/SavingsAccountApplicationPresenter.java
> +        getMvpView().showProgress();
Check view `checkViewAttached();` is attached or not.

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/presenters/SavingsAccountApplicationPresenter.java
> +        getMvpView().showProgress();
Check view `checkViewAttached();` is attached or not.

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/presenters/SavingsAccountWithdrawPresenter.java
> +    CompositeDisposable compositeDisposable;
Make both `Composite....` `DataManager` private

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/presenters/SavingsAccountWithdrawPresenter.java
> +        getMvpView().showProgress();
Check view `checkViewAttached();` is attached or not.

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/presenters/SavingsAccountWithdrawPresenter.java
> +        super.detachView();
Clear `CompositeDisposable` compositeDisposable.clear()

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingsAccountApplicationFragment.java
> +    List<String> productIdList = new ArrayList<>();
Make the above variables private

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingsAccountApplicationFragment.java
> +
Remove this blank line

2019-02-24 05:41 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingsAccountWithdrawFragment.java
> +    SavingsAccountWithdrawPayload payload;
Make above variables private.

2019-03-06 14:06 UTC, therajanmaurya approved these changes

2019-03-06 14:06 UTC, merged