Feat #839 : Support for Editing User Details
openMF/self-service-app pull request #871
Opened 2018-07-14 10:35 UTC by miPlodder

Fixes #839 

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2018-07-14 18:07 UTC, miPlodder commented
**Updated PR**
(I have not submitted change password, as password will change again and we have to change the password 4-5 times to keep the default-password "password". In GIF above, I have checked the API call.)

![pr839_2](https://user-images.githubusercontent.com/22195621/42727135-a3cd9d98-87be-11e8-8917-acacc9139633.gif)
![pr839_3](https://user-images.githubusercontent.com/22195621/42727136-a41d6e9a-87be-11e8-9ea5-18e8ea770df3.gif)

2018-07-14 18:09 UTC, miPlodder commented
@therajanmaurya Please review this PR.

2018-08-15 11:11 UTC, miPlodder commented
@therajanmaurya In this PR, username and clientname is stored incorrectly in SharedPrefs.

2019-02-24 13:50 UTC, therajanmaurya requested changes
@miPlodder Please make above-requested changes and fix that you mentioned username and clientname is stored incorrectly in SharedPrefs:

2019-02-24 13:50 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/presenters/UpdatePasswordPresenter.java
> +    PreferencesHelper preferencesHelper;
Make above variables private

2019-02-24 13:50 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/presenters/UpdatePasswordPresenter.java
> +        getMvpView().showProgress();
Check view is attached or not.

2019-02-24 13:50 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/presenters/UpdatePasswordPresenter.java
> +    public void createAuthenticationToken(String password) {
Update method name `updateAuthenticationToken()`

2019-02-24 13:50 UTC, therajanmaurya commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/UpdatePasswordFragment.java
> +    boolean isFocusLostConfirmPassword = false;
Make above variables private

2019-03-01 16:46 UTC, miPlodder commented on app/src/main/java/org/mifos/mobilebanking/presenters/HomePresenter.java
> +                            preferencesHelper.setClientName(client.getDisplayName());
@therajanmaurya These are the changes that I was talking of.

2019-03-01 17:50 UTC, merged