Fix #883: Modified Beneficiary Template to fix Spinner
openMF/self-service-app pull request #887
Opened 2018-10-01 15:14 UTC by drish1001

Fixes #883 

![883](https://user-images.githubusercontent.com/36307309/46297390-27601f80-c5ba-11e8-85b8-0c8a3197f5c9.gif)

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2018-10-28 06:42 UTC, drish1001 commented
Can you please review this pull request? @miPlodder

2018-12-03 09:01 UTC, miPlodder requested changes

2018-12-03 09:01 UTC, miPlodder commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryApplicationFragment.java
> +            if (cnt == 0) {
@drish1001 Instead of doing this, do list size check on top of the loop.

2018-12-03 09:01 UTC, miPlodder commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryDetailFragment.java
> +        tvTransferLimit.setText(CurrencyUtil.formatCurrency(getActivity(),
@drish1001 Remove these changes to unchanged lines in this file.

2019-01-01 04:51 UTC, miPlodder commented
@drish1001 Make the changes which I have commented above.

2019-01-04 20:14 UTC, therajanmaurya commented
@drish1001 Good catch and sorry for late reply but the fix you did not right. It is pretty straight implementation. Here we need to first fetch the beneficiary template and show data in views and we never call the template again. if it is successfully fetched and setup data views.

Then user will enter data and we make the request to the server. 

Just follow the above scenarios and make the changes. Let me know if you need help.

2019-03-03 11:21 UTC, ShivangiSingh17 commented
Please I would like to work on this issue.

2019-06-01 18:29 UTC, therajanmaurya commented
InActive Closing it

2019-06-01 18:29 UTC, closed without merging