Fix #919: Adapter Attachment Error in RecyclerView when viewing "Charges" and "Accounts" pages
openMF/self-service-app pull request #922
Opened 2018-11-01 07:51 UTC by ethan627hsu

Fixes #919 

Changes improve the declaration and initialization of adapters, and binding data to them properly. These efforts eliminate a non-fatal error log, stating how RecyclerViews were being displayed with no adapter connected to them.

2018-12-21 13:24 UTC, miPlodder requested changes

2018-12-21 13:24 UTC, miPlodder commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/AccountsFragment.java
>          rvAccounts.setLayoutManager(layoutManager);
@ethan627hsu  Changing visibility is not an appropriate solution. Instead, add `adapter` to `recyclerview` inside `onCreateView()` method.

2018-12-21 13:25 UTC, miPlodder commented
@ethan627hsu Make the mentioned changes for both the fragments.

2019-01-04 19:46 UTC, therajanmaurya commented
@ethan627hsu @miPlodder is right. this is not the solution. Let me tell you first when we get 
`E/RecyclerView: No adapter attached; skipping layout`

As we inflate View in `OnCreateView` or `OnCreate`. It inflate the views on screen and when we does not set recycler view adapter then it gives warning, the above warning `E/RecyclerView: No adapter attached; skipping layout`. 

The solution for this warning is to set the adapter with empty list and later when you get the data notify recyclerview about the new data by notifying adapter `adapter.notifyDataSetChanged()`

2019-06-01 18:27 UTC, therajanmaurya commented
InActive Closing It.

2019-06-01 18:27 UTC, closed without merging