Fix #932: Snackbar pops on the FAB on deleting Beneficiary
openMF/self-service-app pull request #939
Opened 2018-11-19 06:10 UTC by ethan627hsu

Fixes #932 

The bug was caused by the snackbar being a part of the wrong layout. Previously, the snackbar had been set to appear in the layout of a BeneficiaryDetailFragment. The snackbar would appear in the BeneficiaryDetailFragment, but the fragment would be quickly destroyed, as the work is done when the fragment is being destroyed. This leaves the snackbar to just "be there" and appear above any other UI elements.

My solution moves the snackbar to be a part of the BeneficiaryListFragment layout, the screen that lists out the beneficiaries and has the FAB. By doing this, the FAB is able to be aware of the snackbar and naturally moves up. I also implemented the same functionality for the "update beneficiary" action, as my solution scales to fix other cases of the issue. No more left out snackbars! 🍫🍬
  
![image](https://user-images.githubusercontent.com/24931732/48689121-e5953380-eb7d-11e8-910c-0e030a5b8a05.png)

2018-11-19 07:56 UTC, miPlodder commented
@ethan627hsu This is not a good solution. Use coordinator layout, follow this link, 

https://stackoverflow.com/a/32777587

2018-11-19 08:00 UTC, ethan627hsu commented
@miPlodder Coordinador layout doesn't help the situation, the problem is that the snackbar is not bound to the correct layout

2018-11-19 08:02 UTC, ethan627hsu commented
Also, the Coordinator layout implementation would be redundant, as the FAB automatically does the detection of the snackbar

2018-11-19 08:11 UTC, miPlodder commented
@ethan627hsu Try that link properly. 

The solution you proposed is not the correct to do these kinds of stuff.

2018-11-19 08:14 UTC, ethan627hsu commented
But how could I implement coordinator layout I'm the list page if the fab is I'm the list page but the snackbar is in the details page? The snackbar would have no reference to the coordiantor layout.

2018-11-19 08:16 UTC, ethan627hsu commented
Do you want me to just change implementation of the snackbar in the list page to include CoordiantorLayout instead of just having it appear?

2018-12-21 15:50 UTC, miPlodder requested changes

2018-12-21 15:50 UTC, miPlodder commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryApplicationFragment.java
> +        castedListFragment.showSnackbar(getString(R.string.beneficiary_updated_successfully));
Don't create variables, do this without any declaring variable in single line. 
For example `(new Object()).showSnackbar()`.

2018-12-21 15:50 UTC, miPlodder commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryDetailFragment.java
> +        castedListFragment.showSnackbar(getString(R.string.beneficiary_deleted_successfully));
Do the same thing here.

2018-12-21 15:50 UTC, miPlodder commented on app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryListFragment.java
> +    private String snackbarContent = null;
What are these changes in this file ? @ethan627hsu

2018-12-21 15:52 UTC, miPlodder commented
@ethan627hsu I just reviewed your PR properly, it appropriate way to do the same. I have requested you some changes. Make those changes.

2019-01-04 19:18 UTC, therajanmaurya commented
Hi @ethan627hsu Sorry for the late reply. The solution you people are discussing is totally wrong. When Beneficiary created successfully then show the Toast, not snack bar. Both things have his won significance. 

Make the changes and let me know.

2019-06-01 16:48 UTC, therajanmaurya commented
Closing it because of inactivity

2019-06-01 16:48 UTC, closed without merging