Feat: Make relevant strings non-translatable
openMF/self-service-app pull request #961
Opened 2018-12-03 10:25 UTC by m-sameer

Fixes #944

The build has been fixed in #959 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2018-12-20 15:01 UTC, miPlodder requested changes

2018-12-20 15:01 UTC, miPlodder commented on app/src/main/res/values/strings.xml
> +    <string name="pref_configuration" translatable="false">pref_configuration</string>
Remove these lines from other translations files.

2018-12-20 15:01 UTC, miPlodder commented on app/src/main/res/values/strings.xml
> +    <string name="contact_email" translatable="false">support@mifos.org</string>
Remove these lines from other translations files.

2018-12-20 15:01 UTC, miPlodder commented on app/src/main/res/values/strings.xml
> +    <string name="help_line_number" translatable="false">8000000000</string>
Remove these lines from other translations files.

2019-01-04 19:13 UTC, therajanmaurya commented
@m-sameer Please make suggested changes.

2019-06-03 04:15 UTC, prashantkh19 commented
#1179 fixes this. @therajanmaurya close this.

2019-06-03 19:16 UTC, closed without merging