Fix #967: resolved unescaped apostrophe in string resource files
openMF/self-service-app pull request #968
Opened 2018-12-15 10:44 UTC by nikhil-sachdeva

Fixes #967

Resolved unescaped apostrophes in fr,pl,in strings.xml files. The app wasn't running on my device before this and now it's running.

2018-12-17 08:32 UTC, luckyman20 approved these changes
@nikhil-sachdeva Good work! This will be merged soon.

2018-12-20 15:07 UTC, miPlodder commented
@nikhil-sachdeva Good job, I think fix for this issue was added in another PR which I have merged. Anyway, you try to rebase and fix the conflict and see if this still persists or not.

2018-12-21 11:49 UTC, miPlodder requested changes

2018-12-21 11:49 UTC, miPlodder commented on app/src/main/res/values-fr/strings.xml
> +
Remove this unwanted space.

2018-12-21 11:49 UTC, miPlodder commented on app/src/main/res/values-fr/strings.xml
> +        <item>Pour demander un compte de crédit, cliquez sur \ "Signaler la demande de prêt \" sur l'écran d'accueil.</item>
\ " - remove space in between.
l'écran d'accueil - add escape character at both the apostrophe.

2018-12-22 13:26 UTC, miPlodder commented
@nikhil-sachdeva Squash your commits.

2018-12-23 18:49 UTC, miPlodder commented
@nikhil-sachdeva Fix the conflict.

2018-12-24 14:00 UTC, nikhil-sachdeva commented
Every time I fix the conflict on github, two commits are made, I pull the branch to my local repo to squash the commits, pushing it again shows merge conflicts. Help me

2018-12-25 06:17 UTC, luckyman20 commented
Don't fix the conflicts here, fix them on your local machine.

2018-12-25 10:54 UTC, closed without merging